/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/evergram.proto */

#ifndef PROTOBUF_C_proto_2fevergram_2eproto__INCLUDED
#define PROTOBUF_C_proto_2fevergram_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Evergram__ClientHello Evergram__ClientHello;
typedef struct Evergram__ServerHello Evergram__ServerHello;
typedef struct Evergram__ChatMessage Evergram__ChatMessage;
typedef struct Evergram__Reaction Evergram__Reaction;
typedef struct Evergram__TypingIndicator Evergram__TypingIndicator;
typedef struct Evergram__SystemEvent Evergram__SystemEvent;
typedef struct Evergram__Envelope Evergram__Envelope;


/* --- enums --- */

/*
 * Tipos de Mensagem
 */
typedef enum _Evergram__MessageType {
  EVERGRAM__MESSAGE_TYPE__UNKNOWN = 0,
  EVERGRAM__MESSAGE_TYPE__TEXT_MESSAGE = 1,
  EVERGRAM__MESSAGE_TYPE__REACTION = 2,
  EVERGRAM__MESSAGE_TYPE__TYPING_INDICATOR = 3,
  EVERGRAM__MESSAGE_TYPE__SYSTEM_EVENT = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(EVERGRAM__MESSAGE_TYPE)
} Evergram__MessageType;

/* --- messages --- */

/*
 * Mensagens de Handshake
 */
struct  Evergram__ClientHello
{
  ProtobufCMessage base;
  char *version;
  ProtobufCBinaryData ephemeral_public_key;
  ProtobufCBinaryData nonce;
  char *device_id;
  char *wallet_address;
  ProtobufCBinaryData signature;
};
#define EVERGRAM__CLIENT_HELLO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&evergram__client_hello__descriptor) \
    , (char *)protobuf_c_empty_string, {0,NULL}, {0,NULL}, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, {0,NULL} }


struct  Evergram__ServerHello
{
  ProtobufCMessage base;
  ProtobufCBinaryData server_public_key;
  ProtobufCBinaryData nonce;
  char *session_id;
  protobuf_c_boolean success;
  char *error_message;
};
#define EVERGRAM__SERVER_HELLO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&evergram__server_hello__descriptor) \
    , {0,NULL}, {0,NULL}, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string }


/*
 * Estrutura de Mensagem de Chat
 */
struct  Evergram__ChatMessage
{
  ProtobufCMessage base;
  char *chat_id;
  char *sender_id;
  char *content;
  int64_t timestamp;
  Evergram__MessageType type;
  char *reply_to;
};
#define EVERGRAM__CHAT_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&evergram__chat_message__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, EVERGRAM__MESSAGE_TYPE__UNKNOWN, (char *)protobuf_c_empty_string }


/*
 * Reação
 */
struct  Evergram__Reaction
{
  ProtobufCMessage base;
  char *chat_id;
  char *message_id;
  char *emoji;
  protobuf_c_boolean add;
};
#define EVERGRAM__REACTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&evergram__reaction__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0 }


/*
 * Indicador de Digitação
 */
struct  Evergram__TypingIndicator
{
  ProtobufCMessage base;
  char *chat_id;
  protobuf_c_boolean is_typing;
};
#define EVERGRAM__TYPING_INDICATOR__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&evergram__typing_indicator__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


/*
 * Evento do Sistema
 */
struct  Evergram__SystemEvent
{
  ProtobufCMessage base;
  char *event_type;
  char *data;
};
#define EVERGRAM__SYSTEM_EVENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&evergram__system_event__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


typedef enum {
  EVERGRAM__ENVELOPE__PAYLOAD__NOT_SET = 0,
  EVERGRAM__ENVELOPE__PAYLOAD_CLIENT_HELLO = 1,
  EVERGRAM__ENVELOPE__PAYLOAD_SERVER_HELLO = 2,
  EVERGRAM__ENVELOPE__PAYLOAD_CHAT_MESSAGE = 3,
  EVERGRAM__ENVELOPE__PAYLOAD_REACTION = 4,
  EVERGRAM__ENVELOPE__PAYLOAD_TYPING = 5,
  EVERGRAM__ENVELOPE__PAYLOAD_SYSTEM_EVENT = 6
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(EVERGRAM__ENVELOPE__PAYLOAD__CASE)
} Evergram__Envelope__PayloadCase;

/*
 * Wrapper principal para transporte
 */
struct  Evergram__Envelope
{
  ProtobufCMessage base;
  ProtobufCBinaryData nonce;
  ProtobufCBinaryData mac;
  Evergram__Envelope__PayloadCase payload_case;
  union {
    Evergram__ClientHello *client_hello;
    Evergram__ServerHello *server_hello;
    Evergram__ChatMessage *chat_message;
    Evergram__Reaction *reaction;
    Evergram__TypingIndicator *typing;
    Evergram__SystemEvent *system_event;
  };
};
#define EVERGRAM__ENVELOPE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&evergram__envelope__descriptor) \
    , {0,NULL}, {0,NULL}, EVERGRAM__ENVELOPE__PAYLOAD__NOT_SET, {0} }


/* Evergram__ClientHello methods */
void   evergram__client_hello__init
                     (Evergram__ClientHello         *message);
size_t evergram__client_hello__get_packed_size
                     (const Evergram__ClientHello   *message);
size_t evergram__client_hello__pack
                     (const Evergram__ClientHello   *message,
                      uint8_t             *out);
size_t evergram__client_hello__pack_to_buffer
                     (const Evergram__ClientHello   *message,
                      ProtobufCBuffer     *buffer);
Evergram__ClientHello *
       evergram__client_hello__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   evergram__client_hello__free_unpacked
                     (Evergram__ClientHello *message,
                      ProtobufCAllocator *allocator);
/* Evergram__ServerHello methods */
void   evergram__server_hello__init
                     (Evergram__ServerHello         *message);
size_t evergram__server_hello__get_packed_size
                     (const Evergram__ServerHello   *message);
size_t evergram__server_hello__pack
                     (const Evergram__ServerHello   *message,
                      uint8_t             *out);
size_t evergram__server_hello__pack_to_buffer
                     (const Evergram__ServerHello   *message,
                      ProtobufCBuffer     *buffer);
Evergram__ServerHello *
       evergram__server_hello__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   evergram__server_hello__free_unpacked
                     (Evergram__ServerHello *message,
                      ProtobufCAllocator *allocator);
/* Evergram__ChatMessage methods */
void   evergram__chat_message__init
                     (Evergram__ChatMessage         *message);
size_t evergram__chat_message__get_packed_size
                     (const Evergram__ChatMessage   *message);
size_t evergram__chat_message__pack
                     (const Evergram__ChatMessage   *message,
                      uint8_t             *out);
size_t evergram__chat_message__pack_to_buffer
                     (const Evergram__ChatMessage   *message,
                      ProtobufCBuffer     *buffer);
Evergram__ChatMessage *
       evergram__chat_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   evergram__chat_message__free_unpacked
                     (Evergram__ChatMessage *message,
                      ProtobufCAllocator *allocator);
/* Evergram__Reaction methods */
void   evergram__reaction__init
                     (Evergram__Reaction         *message);
size_t evergram__reaction__get_packed_size
                     (const Evergram__Reaction   *message);
size_t evergram__reaction__pack
                     (const Evergram__Reaction   *message,
                      uint8_t             *out);
size_t evergram__reaction__pack_to_buffer
                     (const Evergram__Reaction   *message,
                      ProtobufCBuffer     *buffer);
Evergram__Reaction *
       evergram__reaction__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   evergram__reaction__free_unpacked
                     (Evergram__Reaction *message,
                      ProtobufCAllocator *allocator);
/* Evergram__TypingIndicator methods */
void   evergram__typing_indicator__init
                     (Evergram__TypingIndicator         *message);
size_t evergram__typing_indicator__get_packed_size
                     (const Evergram__TypingIndicator   *message);
size_t evergram__typing_indicator__pack
                     (const Evergram__TypingIndicator   *message,
                      uint8_t             *out);
size_t evergram__typing_indicator__pack_to_buffer
                     (const Evergram__TypingIndicator   *message,
                      ProtobufCBuffer     *buffer);
Evergram__TypingIndicator *
       evergram__typing_indicator__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   evergram__typing_indicator__free_unpacked
                     (Evergram__TypingIndicator *message,
                      ProtobufCAllocator *allocator);
/* Evergram__SystemEvent methods */
void   evergram__system_event__init
                     (Evergram__SystemEvent         *message);
size_t evergram__system_event__get_packed_size
                     (const Evergram__SystemEvent   *message);
size_t evergram__system_event__pack
                     (const Evergram__SystemEvent   *message,
                      uint8_t             *out);
size_t evergram__system_event__pack_to_buffer
                     (const Evergram__SystemEvent   *message,
                      ProtobufCBuffer     *buffer);
Evergram__SystemEvent *
       evergram__system_event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   evergram__system_event__free_unpacked
                     (Evergram__SystemEvent *message,
                      ProtobufCAllocator *allocator);
/* Evergram__Envelope methods */
void   evergram__envelope__init
                     (Evergram__Envelope         *message);
size_t evergram__envelope__get_packed_size
                     (const Evergram__Envelope   *message);
size_t evergram__envelope__pack
                     (const Evergram__Envelope   *message,
                      uint8_t             *out);
size_t evergram__envelope__pack_to_buffer
                     (const Evergram__Envelope   *message,
                      ProtobufCBuffer     *buffer);
Evergram__Envelope *
       evergram__envelope__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   evergram__envelope__free_unpacked
                     (Evergram__Envelope *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Evergram__ClientHello_Closure)
                 (const Evergram__ClientHello *message,
                  void *closure_data);
typedef void (*Evergram__ServerHello_Closure)
                 (const Evergram__ServerHello *message,
                  void *closure_data);
typedef void (*Evergram__ChatMessage_Closure)
                 (const Evergram__ChatMessage *message,
                  void *closure_data);
typedef void (*Evergram__Reaction_Closure)
                 (const Evergram__Reaction *message,
                  void *closure_data);
typedef void (*Evergram__TypingIndicator_Closure)
                 (const Evergram__TypingIndicator *message,
                  void *closure_data);
typedef void (*Evergram__SystemEvent_Closure)
                 (const Evergram__SystemEvent *message,
                  void *closure_data);
typedef void (*Evergram__Envelope_Closure)
                 (const Evergram__Envelope *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    evergram__message_type__descriptor;
extern const ProtobufCMessageDescriptor evergram__client_hello__descriptor;
extern const ProtobufCMessageDescriptor evergram__server_hello__descriptor;
extern const ProtobufCMessageDescriptor evergram__chat_message__descriptor;
extern const ProtobufCMessageDescriptor evergram__reaction__descriptor;
extern const ProtobufCMessageDescriptor evergram__typing_indicator__descriptor;
extern const ProtobufCMessageDescriptor evergram__system_event__descriptor;
extern const ProtobufCMessageDescriptor evergram__envelope__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_proto_2fevergram_2eproto__INCLUDED */
