/*
 * Golden interop vectors, generated by tools/gen_interop_vectors.mjs from
 * the TypeScript SDK itself (raw sources through tsx, not a reimplementation).
 *
 * Every value here was produced by the reference implementation and is
 * consumed by tests/test_interop.c, so a passing run proves the two SDKs
 * agree on the wire. Do not edit by hand: regenerate with
 *
 *   TS_SDK=/path/to/evergram-sdk node tools/gen_interop_vectors.mjs \
 *       tests/interop_vectors.h
 */
#ifndef EVERGRAM_TEST_INTEROP_VECTORS_H
#define EVERGRAM_TEST_INTEROP_VECTORS_H

#define INTEROP_WALLET_SEED "sEdVMeXJTg6NzHwF6weP3ms6N6tpgS2"
#define INTEROP_WALLET_ADDRESS "r3VfWwSkWdhYdaqLiQYe3zfQd6x4941hRR"
#define INTEROP_WALLET_PUBLIC_KEY_HEX "EDBD77C1092814C41E3FC85F1CB4BE14C027EAFD8FA41430A947AA1A8A10CA496A"
#define INTEROP_WALLET_PRIVATE_KEY_HEX "EDCAC95EFCF6B9CCBC004601C87811E06824C7376887265299A90DD06CA20E2B96"
#define INTEROP_DEVICE_ID "interop-device-1"
#define INTEROP_DEVICE_PUBLIC_KEY_HEX "358072d6365880d1aeea329adf9121383851ed21a28e3b75e965d0d2cd166254"
#define INTEROP_DEVICE_PRIVATE_KEY_HEX "202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f"
#define INTEROP_CHALLENGE "evergram-auth:r3VfWwSkWdhYdaqLiQYe3zfQd6x4941hRR:interop-device-1:interop-nonce-0001"
#define INTEROP_CHALLENGE_NONCE "interop-nonce-0001"
#define INTEROP_AUTH_PUBLIC_KEY_HEX "EDBD77C1092814C41E3FC85F1CB4BE14C027EAFD8FA41430A947AA1A8A10CA496A"
#define INTEROP_AUTH_SIGNATURE_HEX "B363162B5D59E0AC3A8774A4ACFD92C3CE8EB593BD41FBD5D45AF41BC41123DDA2FB4BF26A24F550D932C6785A7D9F20CE8BA1DC83AE74720A633CC1AC281703"

#define INTEROP_SYM_KEY_HEX "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"
#define INTEROP_SEALED_NONCE_B64 "gIGCg4SFhoeIiYqLjI2Oj5CRkpOUlZaX"
#define INTEROP_SEALED_CIPHERTEXT_B64 "0OWYCXA5ACONreq/jXPMeuc7rfboiWcUV01+cec+LyJ4c0evBsLj3xt+DPlb6t5Y"
#define INTEROP_EPHEMERAL_PUBLIC_KEY_B64 "Z13VdO13iTELPS52gfN5C0ZsdzsVIf7PNld5WDcepS8="

#define INTEROP_MESSAGE_PLAINTEXT "interop message from the reference SDK"
#define INTEROP_MESSAGE_NONCE_B64 "QEFCQ0RFRkdISUpLTE1OT1BRUlNUVVZX"
#define INTEROP_MESSAGE_CIPHERTEXT_B64 "SOIUROXqCmJzbOVFqpF3+yN5IRxIPssKqzwCEgnuP9GoRSk5TTc3rcSnR6ycq+Y6t1FJQqr8"

#define INTEROP_RELAY_PAYLOAD "{\"nonce\":\"wMHCw8TFxsfIycrLzM3Oz9DR0tPU1dbX\",\"ciphertext\":\"MklwD196FD5vwg/yA8w4PubV7vo9+hTNAQq1OuQXtRruOJEq6o0pZEfHxR9uayYNI7kpL3sfjwPCbGz+dPPe09XfXCKvD3FEGJqZo17Lt7JZi4XxLXQawY4dQNZiAWamygBQYlh14ZHsJ8Xzbd77xmHf5Yg=\"}"
#define INTEROP_RELAY_TEXT "hello from the visitor"
#define INTEROP_RELAY_SENDER "1:rVisitor"
#define INTEROP_RELAY_MSG_ID "interop-relay-1"

#define INTEROP_PAYMENT_REQUEST "{\"type\":\"payment_request\",\"requestId\":\"11111111-2222-4333-8444-555555555555\",\"amount\":\"10.5\",\"currency\":\"XAH\",\"currencyId\":\"EVR_XAHAU\",\"note\":\"for the group\",\"to\":\"rRequesterAddress\",\"toIdentityKey\":\"1:rRequesterAddress\"}"
#define INTEROP_PAYMENT_RECEIPT "{\"type\":\"payment_receipt\",\"requestId\":\"11111111-2222-4333-8444-555555555555\",\"txHash\":\"DEADBEEF\",\"amount\":\"10.5\",\"currency\":\"XAH\",\"currencyId\":\"EVR_XAHAU\",\"from\":\"rPayerAddress\",\"fromIdentityKey\":\"1:rPayerAddress\"}"
#define INTEROP_AUDIO "{\"type\":\"audio\",\"mimeType\":\"audio/ogg\",\"durationMs\":1500,\"size\":16,\"payload\":\"AAECAwQFBgcICQoLDA0ODw==\"}"

#endif /* EVERGRAM_TEST_INTEROP_VECTORS_H */
