/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: evergram.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "evergram.pb-c.h"
void   evergram__handshake_request__init
                     (Evergram__HandshakeRequest         *message)
{
  static const Evergram__HandshakeRequest init_value = EVERGRAM__HANDSHAKE_REQUEST__INIT;
  *message = init_value;
}
size_t evergram__handshake_request__get_packed_size
                     (const Evergram__HandshakeRequest *message)
{
  assert(message->base.descriptor == &evergram__handshake_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t evergram__handshake_request__pack
                     (const Evergram__HandshakeRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &evergram__handshake_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t evergram__handshake_request__pack_to_buffer
                     (const Evergram__HandshakeRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &evergram__handshake_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Evergram__HandshakeRequest *
       evergram__handshake_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Evergram__HandshakeRequest *)
     protobuf_c_message_unpack (&evergram__handshake_request__descriptor,
                                allocator, len, data);
}
void   evergram__handshake_request__free_unpacked
                     (Evergram__HandshakeRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &evergram__handshake_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   evergram__handshake_response__init
                     (Evergram__HandshakeResponse         *message)
{
  static const Evergram__HandshakeResponse init_value = EVERGRAM__HANDSHAKE_RESPONSE__INIT;
  *message = init_value;
}
size_t evergram__handshake_response__get_packed_size
                     (const Evergram__HandshakeResponse *message)
{
  assert(message->base.descriptor == &evergram__handshake_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t evergram__handshake_response__pack
                     (const Evergram__HandshakeResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &evergram__handshake_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t evergram__handshake_response__pack_to_buffer
                     (const Evergram__HandshakeResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &evergram__handshake_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Evergram__HandshakeResponse *
       evergram__handshake_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Evergram__HandshakeResponse *)
     protobuf_c_message_unpack (&evergram__handshake_response__descriptor,
                                allocator, len, data);
}
void   evergram__handshake_response__free_unpacked
                     (Evergram__HandshakeResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &evergram__handshake_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   evergram__auth_request__init
                     (Evergram__AuthRequest         *message)
{
  static const Evergram__AuthRequest init_value = EVERGRAM__AUTH_REQUEST__INIT;
  *message = init_value;
}
size_t evergram__auth_request__get_packed_size
                     (const Evergram__AuthRequest *message)
{
  assert(message->base.descriptor == &evergram__auth_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t evergram__auth_request__pack
                     (const Evergram__AuthRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &evergram__auth_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t evergram__auth_request__pack_to_buffer
                     (const Evergram__AuthRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &evergram__auth_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Evergram__AuthRequest *
       evergram__auth_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Evergram__AuthRequest *)
     protobuf_c_message_unpack (&evergram__auth_request__descriptor,
                                allocator, len, data);
}
void   evergram__auth_request__free_unpacked
                     (Evergram__AuthRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &evergram__auth_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   evergram__auth_response__init
                     (Evergram__AuthResponse         *message)
{
  static const Evergram__AuthResponse init_value = EVERGRAM__AUTH_RESPONSE__INIT;
  *message = init_value;
}
size_t evergram__auth_response__get_packed_size
                     (const Evergram__AuthResponse *message)
{
  assert(message->base.descriptor == &evergram__auth_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t evergram__auth_response__pack
                     (const Evergram__AuthResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &evergram__auth_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t evergram__auth_response__pack_to_buffer
                     (const Evergram__AuthResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &evergram__auth_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Evergram__AuthResponse *
       evergram__auth_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Evergram__AuthResponse *)
     protobuf_c_message_unpack (&evergram__auth_response__descriptor,
                                allocator, len, data);
}
void   evergram__auth_response__free_unpacked
                     (Evergram__AuthResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &evergram__auth_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   evergram__message__init
                     (Evergram__Message         *message)
{
  static const Evergram__Message init_value = EVERGRAM__MESSAGE__INIT;
  *message = init_value;
}
size_t evergram__message__get_packed_size
                     (const Evergram__Message *message)
{
  assert(message->base.descriptor == &evergram__message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t evergram__message__pack
                     (const Evergram__Message *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &evergram__message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t evergram__message__pack_to_buffer
                     (const Evergram__Message *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &evergram__message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Evergram__Message *
       evergram__message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Evergram__Message *)
     protobuf_c_message_unpack (&evergram__message__descriptor,
                                allocator, len, data);
}
void   evergram__message__free_unpacked
                     (Evergram__Message *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &evergram__message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   evergram__attachment__init
                     (Evergram__Attachment         *message)
{
  static const Evergram__Attachment init_value = EVERGRAM__ATTACHMENT__INIT;
  *message = init_value;
}
size_t evergram__attachment__get_packed_size
                     (const Evergram__Attachment *message)
{
  assert(message->base.descriptor == &evergram__attachment__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t evergram__attachment__pack
                     (const Evergram__Attachment *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &evergram__attachment__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t evergram__attachment__pack_to_buffer
                     (const Evergram__Attachment *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &evergram__attachment__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Evergram__Attachment *
       evergram__attachment__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Evergram__Attachment *)
     protobuf_c_message_unpack (&evergram__attachment__descriptor,
                                allocator, len, data);
}
void   evergram__attachment__free_unpacked
                     (Evergram__Attachment *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &evergram__attachment__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   evergram__chat__init
                     (Evergram__Chat         *message)
{
  static const Evergram__Chat init_value = EVERGRAM__CHAT__INIT;
  *message = init_value;
}
size_t evergram__chat__get_packed_size
                     (const Evergram__Chat *message)
{
  assert(message->base.descriptor == &evergram__chat__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t evergram__chat__pack
                     (const Evergram__Chat *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &evergram__chat__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t evergram__chat__pack_to_buffer
                     (const Evergram__Chat *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &evergram__chat__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Evergram__Chat *
       evergram__chat__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Evergram__Chat *)
     protobuf_c_message_unpack (&evergram__chat__descriptor,
                                allocator, len, data);
}
void   evergram__chat__free_unpacked
                     (Evergram__Chat *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &evergram__chat__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   evergram__create_chat_request__init
                     (Evergram__CreateChatRequest         *message)
{
  static const Evergram__CreateChatRequest init_value = EVERGRAM__CREATE_CHAT_REQUEST__INIT;
  *message = init_value;
}
size_t evergram__create_chat_request__get_packed_size
                     (const Evergram__CreateChatRequest *message)
{
  assert(message->base.descriptor == &evergram__create_chat_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t evergram__create_chat_request__pack
                     (const Evergram__CreateChatRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &evergram__create_chat_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t evergram__create_chat_request__pack_to_buffer
                     (const Evergram__CreateChatRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &evergram__create_chat_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Evergram__CreateChatRequest *
       evergram__create_chat_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Evergram__CreateChatRequest *)
     protobuf_c_message_unpack (&evergram__create_chat_request__descriptor,
                                allocator, len, data);
}
void   evergram__create_chat_request__free_unpacked
                     (Evergram__CreateChatRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &evergram__create_chat_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   evergram__add_participant_request__init
                     (Evergram__AddParticipantRequest         *message)
{
  static const Evergram__AddParticipantRequest init_value = EVERGRAM__ADD_PARTICIPANT_REQUEST__INIT;
  *message = init_value;
}
size_t evergram__add_participant_request__get_packed_size
                     (const Evergram__AddParticipantRequest *message)
{
  assert(message->base.descriptor == &evergram__add_participant_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t evergram__add_participant_request__pack
                     (const Evergram__AddParticipantRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &evergram__add_participant_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t evergram__add_participant_request__pack_to_buffer
                     (const Evergram__AddParticipantRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &evergram__add_participant_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Evergram__AddParticipantRequest *
       evergram__add_participant_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Evergram__AddParticipantRequest *)
     protobuf_c_message_unpack (&evergram__add_participant_request__descriptor,
                                allocator, len, data);
}
void   evergram__add_participant_request__free_unpacked
                     (Evergram__AddParticipantRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &evergram__add_participant_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   evergram__remove_participant_request__init
                     (Evergram__RemoveParticipantRequest         *message)
{
  static const Evergram__RemoveParticipantRequest init_value = EVERGRAM__REMOVE_PARTICIPANT_REQUEST__INIT;
  *message = init_value;
}
size_t evergram__remove_participant_request__get_packed_size
                     (const Evergram__RemoveParticipantRequest *message)
{
  assert(message->base.descriptor == &evergram__remove_participant_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t evergram__remove_participant_request__pack
                     (const Evergram__RemoveParticipantRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &evergram__remove_participant_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t evergram__remove_participant_request__pack_to_buffer
                     (const Evergram__RemoveParticipantRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &evergram__remove_participant_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Evergram__RemoveParticipantRequest *
       evergram__remove_participant_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Evergram__RemoveParticipantRequest *)
     protobuf_c_message_unpack (&evergram__remove_participant_request__descriptor,
                                allocator, len, data);
}
void   evergram__remove_participant_request__free_unpacked
                     (Evergram__RemoveParticipantRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &evergram__remove_participant_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   evergram__user_profile__init
                     (Evergram__UserProfile         *message)
{
  static const Evergram__UserProfile init_value = EVERGRAM__USER_PROFILE__INIT;
  *message = init_value;
}
size_t evergram__user_profile__get_packed_size
                     (const Evergram__UserProfile *message)
{
  assert(message->base.descriptor == &evergram__user_profile__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t evergram__user_profile__pack
                     (const Evergram__UserProfile *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &evergram__user_profile__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t evergram__user_profile__pack_to_buffer
                     (const Evergram__UserProfile *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &evergram__user_profile__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Evergram__UserProfile *
       evergram__user_profile__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Evergram__UserProfile *)
     protobuf_c_message_unpack (&evergram__user_profile__descriptor,
                                allocator, len, data);
}
void   evergram__user_profile__free_unpacked
                     (Evergram__UserProfile *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &evergram__user_profile__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   evergram__set_profile_request__init
                     (Evergram__SetProfileRequest         *message)
{
  static const Evergram__SetProfileRequest init_value = EVERGRAM__SET_PROFILE_REQUEST__INIT;
  *message = init_value;
}
size_t evergram__set_profile_request__get_packed_size
                     (const Evergram__SetProfileRequest *message)
{
  assert(message->base.descriptor == &evergram__set_profile_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t evergram__set_profile_request__pack
                     (const Evergram__SetProfileRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &evergram__set_profile_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t evergram__set_profile_request__pack_to_buffer
                     (const Evergram__SetProfileRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &evergram__set_profile_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Evergram__SetProfileRequest *
       evergram__set_profile_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Evergram__SetProfileRequest *)
     protobuf_c_message_unpack (&evergram__set_profile_request__descriptor,
                                allocator, len, data);
}
void   evergram__set_profile_request__free_unpacked
                     (Evergram__SetProfileRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &evergram__set_profile_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   evergram__reaction__init
                     (Evergram__Reaction         *message)
{
  static const Evergram__Reaction init_value = EVERGRAM__REACTION__INIT;
  *message = init_value;
}
size_t evergram__reaction__get_packed_size
                     (const Evergram__Reaction *message)
{
  assert(message->base.descriptor == &evergram__reaction__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t evergram__reaction__pack
                     (const Evergram__Reaction *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &evergram__reaction__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t evergram__reaction__pack_to_buffer
                     (const Evergram__Reaction *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &evergram__reaction__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Evergram__Reaction *
       evergram__reaction__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Evergram__Reaction *)
     protobuf_c_message_unpack (&evergram__reaction__descriptor,
                                allocator, len, data);
}
void   evergram__reaction__free_unpacked
                     (Evergram__Reaction *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &evergram__reaction__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   evergram__send_reaction_request__init
                     (Evergram__SendReactionRequest         *message)
{
  static const Evergram__SendReactionRequest init_value = EVERGRAM__SEND_REACTION_REQUEST__INIT;
  *message = init_value;
}
size_t evergram__send_reaction_request__get_packed_size
                     (const Evergram__SendReactionRequest *message)
{
  assert(message->base.descriptor == &evergram__send_reaction_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t evergram__send_reaction_request__pack
                     (const Evergram__SendReactionRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &evergram__send_reaction_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t evergram__send_reaction_request__pack_to_buffer
                     (const Evergram__SendReactionRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &evergram__send_reaction_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Evergram__SendReactionRequest *
       evergram__send_reaction_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Evergram__SendReactionRequest *)
     protobuf_c_message_unpack (&evergram__send_reaction_request__descriptor,
                                allocator, len, data);
}
void   evergram__send_reaction_request__free_unpacked
                     (Evergram__SendReactionRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &evergram__send_reaction_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   evergram__typing_indicator__init
                     (Evergram__TypingIndicator         *message)
{
  static const Evergram__TypingIndicator init_value = EVERGRAM__TYPING_INDICATOR__INIT;
  *message = init_value;
}
size_t evergram__typing_indicator__get_packed_size
                     (const Evergram__TypingIndicator *message)
{
  assert(message->base.descriptor == &evergram__typing_indicator__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t evergram__typing_indicator__pack
                     (const Evergram__TypingIndicator *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &evergram__typing_indicator__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t evergram__typing_indicator__pack_to_buffer
                     (const Evergram__TypingIndicator *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &evergram__typing_indicator__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Evergram__TypingIndicator *
       evergram__typing_indicator__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Evergram__TypingIndicator *)
     protobuf_c_message_unpack (&evergram__typing_indicator__descriptor,
                                allocator, len, data);
}
void   evergram__typing_indicator__free_unpacked
                     (Evergram__TypingIndicator *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &evergram__typing_indicator__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   evergram__encrypted_envelope__init
                     (Evergram__EncryptedEnvelope         *message)
{
  static const Evergram__EncryptedEnvelope init_value = EVERGRAM__ENCRYPTED_ENVELOPE__INIT;
  *message = init_value;
}
size_t evergram__encrypted_envelope__get_packed_size
                     (const Evergram__EncryptedEnvelope *message)
{
  assert(message->base.descriptor == &evergram__encrypted_envelope__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t evergram__encrypted_envelope__pack
                     (const Evergram__EncryptedEnvelope *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &evergram__encrypted_envelope__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t evergram__encrypted_envelope__pack_to_buffer
                     (const Evergram__EncryptedEnvelope *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &evergram__encrypted_envelope__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Evergram__EncryptedEnvelope *
       evergram__encrypted_envelope__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Evergram__EncryptedEnvelope *)
     protobuf_c_message_unpack (&evergram__encrypted_envelope__descriptor,
                                allocator, len, data);
}
void   evergram__encrypted_envelope__free_unpacked
                     (Evergram__EncryptedEnvelope *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &evergram__encrypted_envelope__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   evergram__protocol_message__init
                     (Evergram__ProtocolMessage         *message)
{
  static const Evergram__ProtocolMessage init_value = EVERGRAM__PROTOCOL_MESSAGE__INIT;
  *message = init_value;
}
size_t evergram__protocol_message__get_packed_size
                     (const Evergram__ProtocolMessage *message)
{
  assert(message->base.descriptor == &evergram__protocol_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t evergram__protocol_message__pack
                     (const Evergram__ProtocolMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &evergram__protocol_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t evergram__protocol_message__pack_to_buffer
                     (const Evergram__ProtocolMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &evergram__protocol_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Evergram__ProtocolMessage *
       evergram__protocol_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Evergram__ProtocolMessage *)
     protobuf_c_message_unpack (&evergram__protocol_message__descriptor,
                                allocator, len, data);
}
void   evergram__protocol_message__free_unpacked
                     (Evergram__ProtocolMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &evergram__protocol_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   evergram__error_response__init
                     (Evergram__ErrorResponse         *message)
{
  static const Evergram__ErrorResponse init_value = EVERGRAM__ERROR_RESPONSE__INIT;
  *message = init_value;
}
size_t evergram__error_response__get_packed_size
                     (const Evergram__ErrorResponse *message)
{
  assert(message->base.descriptor == &evergram__error_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t evergram__error_response__pack
                     (const Evergram__ErrorResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &evergram__error_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t evergram__error_response__pack_to_buffer
                     (const Evergram__ErrorResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &evergram__error_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Evergram__ErrorResponse *
       evergram__error_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Evergram__ErrorResponse *)
     protobuf_c_message_unpack (&evergram__error_response__descriptor,
                                allocator, len, data);
}
void   evergram__error_response__free_unpacked
                     (Evergram__ErrorResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &evergram__error_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor evergram__handshake_request__field_descriptors[3] =
{
  {
    "client_version",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__HandshakeRequest, client_version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_public_key",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Evergram__HandshakeRequest, device_public_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Evergram__HandshakeRequest, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned evergram__handshake_request__field_indices_by_name[] = {
  0,   /* field[0] = client_version */
  1,   /* field[1] = device_public_key */
  2,   /* field[2] = timestamp */
};
static const ProtobufCIntRange evergram__handshake_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor evergram__handshake_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "evergram.HandshakeRequest",
  "HandshakeRequest",
  "Evergram__HandshakeRequest",
  "evergram",
  sizeof(Evergram__HandshakeRequest),
  3,
  evergram__handshake_request__field_descriptors,
  evergram__handshake_request__field_indices_by_name,
  1,  evergram__handshake_request__number_ranges,
  (ProtobufCMessageInit) evergram__handshake_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor evergram__handshake_response__field_descriptors[3] =
{
  {
    "success",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Evergram__HandshakeResponse, success),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "server_nonce",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Evergram__HandshakeResponse, server_nonce),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error_message",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__HandshakeResponse, error_message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned evergram__handshake_response__field_indices_by_name[] = {
  2,   /* field[2] = error_message */
  1,   /* field[1] = server_nonce */
  0,   /* field[0] = success */
};
static const ProtobufCIntRange evergram__handshake_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor evergram__handshake_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "evergram.HandshakeResponse",
  "HandshakeResponse",
  "Evergram__HandshakeResponse",
  "evergram",
  sizeof(Evergram__HandshakeResponse),
  3,
  evergram__handshake_response__field_descriptors,
  evergram__handshake_response__field_indices_by_name,
  1,  evergram__handshake_response__number_ranges,
  (ProtobufCMessageInit) evergram__handshake_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor evergram__auth_request__field_descriptors[3] =
{
  {
    "signature",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Evergram__AuthRequest, signature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wallet_address",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__AuthRequest, wallet_address),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_id",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Evergram__AuthRequest, device_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned evergram__auth_request__field_indices_by_name[] = {
  2,   /* field[2] = device_id */
  0,   /* field[0] = signature */
  1,   /* field[1] = wallet_address */
};
static const ProtobufCIntRange evergram__auth_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor evergram__auth_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "evergram.AuthRequest",
  "AuthRequest",
  "Evergram__AuthRequest",
  "evergram",
  sizeof(Evergram__AuthRequest),
  3,
  evergram__auth_request__field_descriptors,
  evergram__auth_request__field_indices_by_name,
  1,  evergram__auth_request__number_ranges,
  (ProtobufCMessageInit) evergram__auth_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor evergram__auth_response__field_descriptors[3] =
{
  {
    "authenticated",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Evergram__AuthResponse, authenticated),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "session_token",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__AuthResponse, session_token),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "expires_at",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Evergram__AuthResponse, expires_at),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned evergram__auth_response__field_indices_by_name[] = {
  0,   /* field[0] = authenticated */
  2,   /* field[2] = expires_at */
  1,   /* field[1] = session_token */
};
static const ProtobufCIntRange evergram__auth_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor evergram__auth_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "evergram.AuthResponse",
  "AuthResponse",
  "Evergram__AuthResponse",
  "evergram",
  sizeof(Evergram__AuthResponse),
  3,
  evergram__auth_response__field_descriptors,
  evergram__auth_response__field_indices_by_name,
  1,  evergram__auth_response__number_ranges,
  (ProtobufCMessageInit) evergram__auth_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor evergram__message__field_descriptors[8] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__Message, id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "chat_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__Message, chat_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sender_id",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__Message, sender_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "content",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__Message, content),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Evergram__Message, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Evergram__Message, type),
    &evergram__message_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attachments",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Evergram__Message, n_attachments),
    offsetof(Evergram__Message, attachments),
    &evergram__attachment__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Evergram__Message, status),
    &evergram__message_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned evergram__message__field_indices_by_name[] = {
  6,   /* field[6] = attachments */
  1,   /* field[1] = chat_id */
  3,   /* field[3] = content */
  0,   /* field[0] = id */
  2,   /* field[2] = sender_id */
  7,   /* field[7] = status */
  4,   /* field[4] = timestamp */
  5,   /* field[5] = type */
};
static const ProtobufCIntRange evergram__message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor evergram__message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "evergram.Message",
  "Message",
  "Evergram__Message",
  "evergram",
  sizeof(Evergram__Message),
  8,
  evergram__message__field_descriptors,
  evergram__message__field_indices_by_name,
  1,  evergram__message__number_ranges,
  (ProtobufCMessageInit) evergram__message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor evergram__attachment__field_descriptors[5] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__Attachment, id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "url",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__Attachment, url),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mime_type",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__Attachment, mime_type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Evergram__Attachment, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "filename",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__Attachment, filename),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned evergram__attachment__field_indices_by_name[] = {
  4,   /* field[4] = filename */
  0,   /* field[0] = id */
  2,   /* field[2] = mime_type */
  3,   /* field[3] = size */
  1,   /* field[1] = url */
};
static const ProtobufCIntRange evergram__attachment__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor evergram__attachment__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "evergram.Attachment",
  "Attachment",
  "Evergram__Attachment",
  "evergram",
  sizeof(Evergram__Attachment),
  5,
  evergram__attachment__field_descriptors,
  evergram__attachment__field_indices_by_name,
  1,  evergram__attachment__number_ranges,
  (ProtobufCMessageInit) evergram__attachment__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor evergram__chat__field_descriptors[6] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__Chat, id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__Chat, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Evergram__Chat, type),
    &evergram__chat_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "participant_ids",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Evergram__Chat, n_participant_ids),
    offsetof(Evergram__Chat, participant_ids),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "created_at",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Evergram__Chat, created_at),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last_message",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Evergram__Chat, last_message),
    &evergram__message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned evergram__chat__field_indices_by_name[] = {
  4,   /* field[4] = created_at */
  0,   /* field[0] = id */
  5,   /* field[5] = last_message */
  1,   /* field[1] = name */
  3,   /* field[3] = participant_ids */
  2,   /* field[2] = type */
};
static const ProtobufCIntRange evergram__chat__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor evergram__chat__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "evergram.Chat",
  "Chat",
  "Evergram__Chat",
  "evergram",
  sizeof(Evergram__Chat),
  6,
  evergram__chat__field_descriptors,
  evergram__chat__field_indices_by_name,
  1,  evergram__chat__number_ranges,
  (ProtobufCMessageInit) evergram__chat__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor evergram__create_chat_request__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__CreateChatRequest, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Evergram__CreateChatRequest, type),
    &evergram__chat_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "participant_ids",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Evergram__CreateChatRequest, n_participant_ids),
    offsetof(Evergram__CreateChatRequest, participant_ids),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned evergram__create_chat_request__field_indices_by_name[] = {
  0,   /* field[0] = name */
  2,   /* field[2] = participant_ids */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange evergram__create_chat_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor evergram__create_chat_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "evergram.CreateChatRequest",
  "CreateChatRequest",
  "Evergram__CreateChatRequest",
  "evergram",
  sizeof(Evergram__CreateChatRequest),
  3,
  evergram__create_chat_request__field_descriptors,
  evergram__create_chat_request__field_indices_by_name,
  1,  evergram__create_chat_request__number_ranges,
  (ProtobufCMessageInit) evergram__create_chat_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor evergram__add_participant_request__field_descriptors[2] =
{
  {
    "chat_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__AddParticipantRequest, chat_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__AddParticipantRequest, user_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned evergram__add_participant_request__field_indices_by_name[] = {
  0,   /* field[0] = chat_id */
  1,   /* field[1] = user_id */
};
static const ProtobufCIntRange evergram__add_participant_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor evergram__add_participant_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "evergram.AddParticipantRequest",
  "AddParticipantRequest",
  "Evergram__AddParticipantRequest",
  "evergram",
  sizeof(Evergram__AddParticipantRequest),
  2,
  evergram__add_participant_request__field_descriptors,
  evergram__add_participant_request__field_indices_by_name,
  1,  evergram__add_participant_request__number_ranges,
  (ProtobufCMessageInit) evergram__add_participant_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor evergram__remove_participant_request__field_descriptors[2] =
{
  {
    "chat_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__RemoveParticipantRequest, chat_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__RemoveParticipantRequest, user_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned evergram__remove_participant_request__field_indices_by_name[] = {
  0,   /* field[0] = chat_id */
  1,   /* field[1] = user_id */
};
static const ProtobufCIntRange evergram__remove_participant_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor evergram__remove_participant_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "evergram.RemoveParticipantRequest",
  "RemoveParticipantRequest",
  "Evergram__RemoveParticipantRequest",
  "evergram",
  sizeof(Evergram__RemoveParticipantRequest),
  2,
  evergram__remove_participant_request__field_descriptors,
  evergram__remove_participant_request__field_indices_by_name,
  1,  evergram__remove_participant_request__number_ranges,
  (ProtobufCMessageInit) evergram__remove_participant_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor evergram__user_profile__field_descriptors[5] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__UserProfile, id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "display_name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__UserProfile, display_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "avatar_url",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__UserProfile, avatar_url),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bio",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__UserProfile, bio),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "created_at",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Evergram__UserProfile, created_at),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned evergram__user_profile__field_indices_by_name[] = {
  2,   /* field[2] = avatar_url */
  3,   /* field[3] = bio */
  4,   /* field[4] = created_at */
  1,   /* field[1] = display_name */
  0,   /* field[0] = id */
};
static const ProtobufCIntRange evergram__user_profile__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor evergram__user_profile__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "evergram.UserProfile",
  "UserProfile",
  "Evergram__UserProfile",
  "evergram",
  sizeof(Evergram__UserProfile),
  5,
  evergram__user_profile__field_descriptors,
  evergram__user_profile__field_indices_by_name,
  1,  evergram__user_profile__number_ranges,
  (ProtobufCMessageInit) evergram__user_profile__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor evergram__set_profile_request__field_descriptors[3] =
{
  {
    "display_name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__SetProfileRequest, display_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "avatar_url",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__SetProfileRequest, avatar_url),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bio",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__SetProfileRequest, bio),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned evergram__set_profile_request__field_indices_by_name[] = {
  1,   /* field[1] = avatar_url */
  2,   /* field[2] = bio */
  0,   /* field[0] = display_name */
};
static const ProtobufCIntRange evergram__set_profile_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor evergram__set_profile_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "evergram.SetProfileRequest",
  "SetProfileRequest",
  "Evergram__SetProfileRequest",
  "evergram",
  sizeof(Evergram__SetProfileRequest),
  3,
  evergram__set_profile_request__field_descriptors,
  evergram__set_profile_request__field_indices_by_name,
  1,  evergram__set_profile_request__number_ranges,
  (ProtobufCMessageInit) evergram__set_profile_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor evergram__reaction__field_descriptors[4] =
{
  {
    "message_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__Reaction, message_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__Reaction, user_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "emoji",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__Reaction, emoji),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Evergram__Reaction, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned evergram__reaction__field_indices_by_name[] = {
  2,   /* field[2] = emoji */
  0,   /* field[0] = message_id */
  3,   /* field[3] = timestamp */
  1,   /* field[1] = user_id */
};
static const ProtobufCIntRange evergram__reaction__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor evergram__reaction__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "evergram.Reaction",
  "Reaction",
  "Evergram__Reaction",
  "evergram",
  sizeof(Evergram__Reaction),
  4,
  evergram__reaction__field_descriptors,
  evergram__reaction__field_indices_by_name,
  1,  evergram__reaction__number_ranges,
  (ProtobufCMessageInit) evergram__reaction__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor evergram__send_reaction_request__field_descriptors[2] =
{
  {
    "message_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__SendReactionRequest, message_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "emoji",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__SendReactionRequest, emoji),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned evergram__send_reaction_request__field_indices_by_name[] = {
  1,   /* field[1] = emoji */
  0,   /* field[0] = message_id */
};
static const ProtobufCIntRange evergram__send_reaction_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor evergram__send_reaction_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "evergram.SendReactionRequest",
  "SendReactionRequest",
  "Evergram__SendReactionRequest",
  "evergram",
  sizeof(Evergram__SendReactionRequest),
  2,
  evergram__send_reaction_request__field_descriptors,
  evergram__send_reaction_request__field_indices_by_name,
  1,  evergram__send_reaction_request__number_ranges,
  (ProtobufCMessageInit) evergram__send_reaction_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor evergram__typing_indicator__field_descriptors[4] =
{
  {
    "chat_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__TypingIndicator, chat_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__TypingIndicator, user_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_typing",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Evergram__TypingIndicator, is_typing),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Evergram__TypingIndicator, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned evergram__typing_indicator__field_indices_by_name[] = {
  0,   /* field[0] = chat_id */
  2,   /* field[2] = is_typing */
  3,   /* field[3] = timestamp */
  1,   /* field[1] = user_id */
};
static const ProtobufCIntRange evergram__typing_indicator__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor evergram__typing_indicator__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "evergram.TypingIndicator",
  "TypingIndicator",
  "Evergram__TypingIndicator",
  "evergram",
  sizeof(Evergram__TypingIndicator),
  4,
  evergram__typing_indicator__field_descriptors,
  evergram__typing_indicator__field_indices_by_name,
  1,  evergram__typing_indicator__number_ranges,
  (ProtobufCMessageInit) evergram__typing_indicator__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor evergram__encrypted_envelope__field_descriptors[4] =
{
  {
    "encrypted_payload",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Evergram__EncryptedEnvelope, encrypted_payload),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nonce",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Evergram__EncryptedEnvelope, nonce),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sender_device_id",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__EncryptedEnvelope, sender_device_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Evergram__EncryptedEnvelope, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned evergram__encrypted_envelope__field_indices_by_name[] = {
  0,   /* field[0] = encrypted_payload */
  1,   /* field[1] = nonce */
  2,   /* field[2] = sender_device_id */
  3,   /* field[3] = timestamp */
};
static const ProtobufCIntRange evergram__encrypted_envelope__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor evergram__encrypted_envelope__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "evergram.EncryptedEnvelope",
  "EncryptedEnvelope",
  "Evergram__EncryptedEnvelope",
  "evergram",
  sizeof(Evergram__EncryptedEnvelope),
  4,
  evergram__encrypted_envelope__field_descriptors,
  evergram__encrypted_envelope__field_indices_by_name,
  1,  evergram__encrypted_envelope__number_ranges,
  (ProtobufCMessageInit) evergram__encrypted_envelope__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor evergram__protocol_message__field_descriptors[16] =
{
  {
    "handshake_request",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Evergram__ProtocolMessage, payload_case),
    offsetof(Evergram__ProtocolMessage, handshake_request),
    &evergram__handshake_request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "handshake_response",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Evergram__ProtocolMessage, payload_case),
    offsetof(Evergram__ProtocolMessage, handshake_response),
    &evergram__handshake_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "auth_request",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Evergram__ProtocolMessage, payload_case),
    offsetof(Evergram__ProtocolMessage, auth_request),
    &evergram__auth_request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "auth_response",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Evergram__ProtocolMessage, payload_case),
    offsetof(Evergram__ProtocolMessage, auth_response),
    &evergram__auth_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Evergram__ProtocolMessage, payload_case),
    offsetof(Evergram__ProtocolMessage, message),
    &evergram__message__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "chat",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Evergram__ProtocolMessage, payload_case),
    offsetof(Evergram__ProtocolMessage, chat),
    &evergram__chat__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "create_chat_request",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Evergram__ProtocolMessage, payload_case),
    offsetof(Evergram__ProtocolMessage, create_chat_request),
    &evergram__create_chat_request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "add_participant_request",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Evergram__ProtocolMessage, payload_case),
    offsetof(Evergram__ProtocolMessage, add_participant_request),
    &evergram__add_participant_request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "remove_participant_request",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Evergram__ProtocolMessage, payload_case),
    offsetof(Evergram__ProtocolMessage, remove_participant_request),
    &evergram__remove_participant_request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user_profile",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Evergram__ProtocolMessage, payload_case),
    offsetof(Evergram__ProtocolMessage, user_profile),
    &evergram__user_profile__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "set_profile_request",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Evergram__ProtocolMessage, payload_case),
    offsetof(Evergram__ProtocolMessage, set_profile_request),
    &evergram__set_profile_request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reaction",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Evergram__ProtocolMessage, payload_case),
    offsetof(Evergram__ProtocolMessage, reaction),
    &evergram__reaction__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "send_reaction_request",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Evergram__ProtocolMessage, payload_case),
    offsetof(Evergram__ProtocolMessage, send_reaction_request),
    &evergram__send_reaction_request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "typing_indicator",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Evergram__ProtocolMessage, payload_case),
    offsetof(Evergram__ProtocolMessage, typing_indicator),
    &evergram__typing_indicator__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "encrypted_envelope",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Evergram__ProtocolMessage, payload_case),
    offsetof(Evergram__ProtocolMessage, encrypted_envelope),
    &evergram__encrypted_envelope__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error_response",
    16,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Evergram__ProtocolMessage, payload_case),
    offsetof(Evergram__ProtocolMessage, error_response),
    &evergram__error_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned evergram__protocol_message__field_indices_by_name[] = {
  7,   /* field[7] = add_participant_request */
  2,   /* field[2] = auth_request */
  3,   /* field[3] = auth_response */
  5,   /* field[5] = chat */
  6,   /* field[6] = create_chat_request */
  14,   /* field[14] = encrypted_envelope */
  15,   /* field[15] = error_response */
  0,   /* field[0] = handshake_request */
  1,   /* field[1] = handshake_response */
  4,   /* field[4] = message */
  11,   /* field[11] = reaction */
  8,   /* field[8] = remove_participant_request */
  12,   /* field[12] = send_reaction_request */
  10,   /* field[10] = set_profile_request */
  13,   /* field[13] = typing_indicator */
  9,   /* field[9] = user_profile */
};
static const ProtobufCIntRange evergram__protocol_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 16 }
};
const ProtobufCMessageDescriptor evergram__protocol_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "evergram.ProtocolMessage",
  "ProtocolMessage",
  "Evergram__ProtocolMessage",
  "evergram",
  sizeof(Evergram__ProtocolMessage),
  16,
  evergram__protocol_message__field_descriptors,
  evergram__protocol_message__field_indices_by_name,
  1,  evergram__protocol_message__number_ranges,
  (ProtobufCMessageInit) evergram__protocol_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor evergram__error_response__field_descriptors[3] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__ErrorResponse, code),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__ErrorResponse, message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "details",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__ErrorResponse, details),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned evergram__error_response__field_indices_by_name[] = {
  0,   /* field[0] = code */
  2,   /* field[2] = details */
  1,   /* field[1] = message */
};
static const ProtobufCIntRange evergram__error_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor evergram__error_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "evergram.ErrorResponse",
  "ErrorResponse",
  "Evergram__ErrorResponse",
  "evergram",
  sizeof(Evergram__ErrorResponse),
  3,
  evergram__error_response__field_descriptors,
  evergram__error_response__field_indices_by_name,
  1,  evergram__error_response__number_ranges,
  (ProtobufCMessageInit) evergram__error_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue evergram__message_type__enum_values_by_number[7] =
{
  { "MESSAGE_TYPE_UNKNOWN", "EVERGRAM__MESSAGE_TYPE__MESSAGE_TYPE_UNKNOWN", 0 },
  { "MESSAGE_TYPE_TEXT", "EVERGRAM__MESSAGE_TYPE__MESSAGE_TYPE_TEXT", 1 },
  { "MESSAGE_TYPE_IMAGE", "EVERGRAM__MESSAGE_TYPE__MESSAGE_TYPE_IMAGE", 2 },
  { "MESSAGE_TYPE_VIDEO", "EVERGRAM__MESSAGE_TYPE__MESSAGE_TYPE_VIDEO", 3 },
  { "MESSAGE_TYPE_AUDIO", "EVERGRAM__MESSAGE_TYPE__MESSAGE_TYPE_AUDIO", 4 },
  { "MESSAGE_TYPE_FILE", "EVERGRAM__MESSAGE_TYPE__MESSAGE_TYPE_FILE", 5 },
  { "MESSAGE_TYPE_SYSTEM", "EVERGRAM__MESSAGE_TYPE__MESSAGE_TYPE_SYSTEM", 6 },
};
static const ProtobufCIntRange evergram__message_type__value_ranges[] = {
{0, 0},{0, 7}
};
static const ProtobufCEnumValueIndex evergram__message_type__enum_values_by_name[7] =
{
  { "MESSAGE_TYPE_AUDIO", 4 },
  { "MESSAGE_TYPE_FILE", 5 },
  { "MESSAGE_TYPE_IMAGE", 2 },
  { "MESSAGE_TYPE_SYSTEM", 6 },
  { "MESSAGE_TYPE_TEXT", 1 },
  { "MESSAGE_TYPE_UNKNOWN", 0 },
  { "MESSAGE_TYPE_VIDEO", 3 },
};
const ProtobufCEnumDescriptor evergram__message_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "evergram.MessageType",
  "MessageType",
  "Evergram__MessageType",
  "evergram",
  7,
  evergram__message_type__enum_values_by_number,
  7,
  evergram__message_type__enum_values_by_name,
  1,
  evergram__message_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue evergram__message_status__enum_values_by_number[5] =
{
  { "STATUS_UNKNOWN", "EVERGRAM__MESSAGE_STATUS__STATUS_UNKNOWN", 0 },
  { "STATUS_SENT", "EVERGRAM__MESSAGE_STATUS__STATUS_SENT", 1 },
  { "STATUS_DELIVERED", "EVERGRAM__MESSAGE_STATUS__STATUS_DELIVERED", 2 },
  { "STATUS_READ", "EVERGRAM__MESSAGE_STATUS__STATUS_READ", 3 },
  { "STATUS_FAILED", "EVERGRAM__MESSAGE_STATUS__STATUS_FAILED", 4 },
};
static const ProtobufCIntRange evergram__message_status__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex evergram__message_status__enum_values_by_name[5] =
{
  { "STATUS_DELIVERED", 2 },
  { "STATUS_FAILED", 4 },
  { "STATUS_READ", 3 },
  { "STATUS_SENT", 1 },
  { "STATUS_UNKNOWN", 0 },
};
const ProtobufCEnumDescriptor evergram__message_status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "evergram.MessageStatus",
  "MessageStatus",
  "Evergram__MessageStatus",
  "evergram",
  5,
  evergram__message_status__enum_values_by_number,
  5,
  evergram__message_status__enum_values_by_name,
  1,
  evergram__message_status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue evergram__chat_type__enum_values_by_number[3] =
{
  { "CHAT_TYPE_PRIVATE", "EVERGRAM__CHAT_TYPE__CHAT_TYPE_PRIVATE", 0 },
  { "CHAT_TYPE_GROUP", "EVERGRAM__CHAT_TYPE__CHAT_TYPE_GROUP", 1 },
  { "CHAT_TYPE_CHANNEL", "EVERGRAM__CHAT_TYPE__CHAT_TYPE_CHANNEL", 2 },
};
static const ProtobufCIntRange evergram__chat_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex evergram__chat_type__enum_values_by_name[3] =
{
  { "CHAT_TYPE_CHANNEL", 2 },
  { "CHAT_TYPE_GROUP", 1 },
  { "CHAT_TYPE_PRIVATE", 0 },
};
const ProtobufCEnumDescriptor evergram__chat_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "evergram.ChatType",
  "ChatType",
  "Evergram__ChatType",
  "evergram",
  3,
  evergram__chat_type__enum_values_by_number,
  3,
  evergram__chat_type__enum_values_by_name,
  1,
  evergram__chat_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
