/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: evergram.proto */

#ifndef PROTOBUF_C_evergram_2eproto__INCLUDED
#define PROTOBUF_C_evergram_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Evergram__HandshakeRequest Evergram__HandshakeRequest;
typedef struct Evergram__HandshakeResponse Evergram__HandshakeResponse;
typedef struct Evergram__AuthRequest Evergram__AuthRequest;
typedef struct Evergram__AuthResponse Evergram__AuthResponse;
typedef struct Evergram__Message Evergram__Message;
typedef struct Evergram__Attachment Evergram__Attachment;
typedef struct Evergram__Chat Evergram__Chat;
typedef struct Evergram__CreateChatRequest Evergram__CreateChatRequest;
typedef struct Evergram__AddParticipantRequest Evergram__AddParticipantRequest;
typedef struct Evergram__RemoveParticipantRequest Evergram__RemoveParticipantRequest;
typedef struct Evergram__UserProfile Evergram__UserProfile;
typedef struct Evergram__SetProfileRequest Evergram__SetProfileRequest;
typedef struct Evergram__Reaction Evergram__Reaction;
typedef struct Evergram__SendReactionRequest Evergram__SendReactionRequest;
typedef struct Evergram__TypingIndicator Evergram__TypingIndicator;
typedef struct Evergram__EncryptedEnvelope Evergram__EncryptedEnvelope;
typedef struct Evergram__ProtocolMessage Evergram__ProtocolMessage;
typedef struct Evergram__ErrorResponse Evergram__ErrorResponse;


/* --- enums --- */

typedef enum _Evergram__MessageType {
  EVERGRAM__MESSAGE_TYPE__MESSAGE_TYPE_UNKNOWN = 0,
  EVERGRAM__MESSAGE_TYPE__MESSAGE_TYPE_TEXT = 1,
  EVERGRAM__MESSAGE_TYPE__MESSAGE_TYPE_IMAGE = 2,
  EVERGRAM__MESSAGE_TYPE__MESSAGE_TYPE_VIDEO = 3,
  EVERGRAM__MESSAGE_TYPE__MESSAGE_TYPE_AUDIO = 4,
  EVERGRAM__MESSAGE_TYPE__MESSAGE_TYPE_FILE = 5,
  EVERGRAM__MESSAGE_TYPE__MESSAGE_TYPE_SYSTEM = 6
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(EVERGRAM__MESSAGE_TYPE)
} Evergram__MessageType;
typedef enum _Evergram__MessageStatus {
  EVERGRAM__MESSAGE_STATUS__STATUS_UNKNOWN = 0,
  EVERGRAM__MESSAGE_STATUS__STATUS_SENT = 1,
  EVERGRAM__MESSAGE_STATUS__STATUS_DELIVERED = 2,
  EVERGRAM__MESSAGE_STATUS__STATUS_READ = 3,
  EVERGRAM__MESSAGE_STATUS__STATUS_FAILED = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(EVERGRAM__MESSAGE_STATUS)
} Evergram__MessageStatus;
typedef enum _Evergram__ChatType {
  EVERGRAM__CHAT_TYPE__CHAT_TYPE_PRIVATE = 0,
  EVERGRAM__CHAT_TYPE__CHAT_TYPE_GROUP = 1,
  EVERGRAM__CHAT_TYPE__CHAT_TYPE_CHANNEL = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(EVERGRAM__CHAT_TYPE)
} Evergram__ChatType;

/* --- messages --- */

/*
 * Mensagens de Handshake e Conexão
 */
struct  Evergram__HandshakeRequest
{
  ProtobufCMessage base;
  char *client_version;
  ProtobufCBinaryData device_public_key;
  uint64_t timestamp;
};
#define EVERGRAM__HANDSHAKE_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&evergram__handshake_request__descriptor) \
    , (char *)protobuf_c_empty_string, {0,NULL}, 0 }


struct  Evergram__HandshakeResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean success;
  ProtobufCBinaryData server_nonce;
  char *error_message;
};
#define EVERGRAM__HANDSHAKE_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&evergram__handshake_response__descriptor) \
    , 0, {0,NULL}, (char *)protobuf_c_empty_string }


struct  Evergram__AuthRequest
{
  ProtobufCMessage base;
  ProtobufCBinaryData signature;
  char *wallet_address;
  ProtobufCBinaryData device_id;
};
#define EVERGRAM__AUTH_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&evergram__auth_request__descriptor) \
    , {0,NULL}, (char *)protobuf_c_empty_string, {0,NULL} }


struct  Evergram__AuthResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean authenticated;
  char *session_token;
  uint64_t expires_at;
};
#define EVERGRAM__AUTH_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&evergram__auth_response__descriptor) \
    , 0, (char *)protobuf_c_empty_string, 0 }


/*
 * Estruturas de Mensagem
 */
struct  Evergram__Message
{
  ProtobufCMessage base;
  char *id;
  char *chat_id;
  char *sender_id;
  char *content;
  uint64_t timestamp;
  Evergram__MessageType type;
  size_t n_attachments;
  Evergram__Attachment **attachments;
  Evergram__MessageStatus status;
};
#define EVERGRAM__MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&evergram__message__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, EVERGRAM__MESSAGE_TYPE__MESSAGE_TYPE_UNKNOWN, 0,NULL, EVERGRAM__MESSAGE_STATUS__STATUS_UNKNOWN }


struct  Evergram__Attachment
{
  ProtobufCMessage base;
  char *id;
  char *url;
  char *mime_type;
  uint64_t size;
  char *filename;
};
#define EVERGRAM__ATTACHMENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&evergram__attachment__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string }


/*
 * Chat e Participantes
 */
struct  Evergram__Chat
{
  ProtobufCMessage base;
  char *id;
  char *name;
  Evergram__ChatType type;
  size_t n_participant_ids;
  char **participant_ids;
  uint64_t created_at;
  Evergram__Message *last_message;
};
#define EVERGRAM__CHAT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&evergram__chat__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, EVERGRAM__CHAT_TYPE__CHAT_TYPE_PRIVATE, 0,NULL, 0, NULL }


struct  Evergram__CreateChatRequest
{
  ProtobufCMessage base;
  char *name;
  Evergram__ChatType type;
  size_t n_participant_ids;
  char **participant_ids;
};
#define EVERGRAM__CREATE_CHAT_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&evergram__create_chat_request__descriptor) \
    , (char *)protobuf_c_empty_string, EVERGRAM__CHAT_TYPE__CHAT_TYPE_PRIVATE, 0,NULL }


struct  Evergram__AddParticipantRequest
{
  ProtobufCMessage base;
  char *chat_id;
  char *user_id;
};
#define EVERGRAM__ADD_PARTICIPANT_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&evergram__add_participant_request__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  Evergram__RemoveParticipantRequest
{
  ProtobufCMessage base;
  char *chat_id;
  char *user_id;
};
#define EVERGRAM__REMOVE_PARTICIPANT_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&evergram__remove_participant_request__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/*
 * Perfil de Usuário
 */
struct  Evergram__UserProfile
{
  ProtobufCMessage base;
  char *id;
  char *display_name;
  char *avatar_url;
  char *bio;
  uint64_t created_at;
};
#define EVERGRAM__USER_PROFILE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&evergram__user_profile__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0 }


struct  Evergram__SetProfileRequest
{
  ProtobufCMessage base;
  char *display_name;
  char *avatar_url;
  char *bio;
};
#define EVERGRAM__SET_PROFILE_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&evergram__set_profile_request__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/*
 * Reações
 */
struct  Evergram__Reaction
{
  ProtobufCMessage base;
  char *message_id;
  char *user_id;
  char *emoji;
  uint64_t timestamp;
};
#define EVERGRAM__REACTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&evergram__reaction__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0 }


struct  Evergram__SendReactionRequest
{
  ProtobufCMessage base;
  char *message_id;
  char *emoji;
};
#define EVERGRAM__SEND_REACTION_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&evergram__send_reaction_request__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/*
 * Typing Indicator
 */
struct  Evergram__TypingIndicator
{
  ProtobufCMessage base;
  char *chat_id;
  char *user_id;
  protobuf_c_boolean is_typing;
  uint64_t timestamp;
};
#define EVERGRAM__TYPING_INDICATOR__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&evergram__typing_indicator__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0 }


/*
 * Envelope criptografado para transporte
 */
struct  Evergram__EncryptedEnvelope
{
  ProtobufCMessage base;
  ProtobufCBinaryData encrypted_payload;
  ProtobufCBinaryData nonce;
  char *sender_device_id;
  uint64_t timestamp;
};
#define EVERGRAM__ENCRYPTED_ENVELOPE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&evergram__encrypted_envelope__descriptor) \
    , {0,NULL}, {0,NULL}, (char *)protobuf_c_empty_string, 0 }


typedef enum {
  EVERGRAM__PROTOCOL_MESSAGE__PAYLOAD__NOT_SET = 0,
  EVERGRAM__PROTOCOL_MESSAGE__PAYLOAD_HANDSHAKE_REQUEST = 1,
  EVERGRAM__PROTOCOL_MESSAGE__PAYLOAD_HANDSHAKE_RESPONSE = 2,
  EVERGRAM__PROTOCOL_MESSAGE__PAYLOAD_AUTH_REQUEST = 3,
  EVERGRAM__PROTOCOL_MESSAGE__PAYLOAD_AUTH_RESPONSE = 4,
  EVERGRAM__PROTOCOL_MESSAGE__PAYLOAD_MESSAGE = 5,
  EVERGRAM__PROTOCOL_MESSAGE__PAYLOAD_CHAT = 6,
  EVERGRAM__PROTOCOL_MESSAGE__PAYLOAD_CREATE_CHAT_REQUEST = 7,
  EVERGRAM__PROTOCOL_MESSAGE__PAYLOAD_ADD_PARTICIPANT_REQUEST = 8,
  EVERGRAM__PROTOCOL_MESSAGE__PAYLOAD_REMOVE_PARTICIPANT_REQUEST = 9,
  EVERGRAM__PROTOCOL_MESSAGE__PAYLOAD_USER_PROFILE = 10,
  EVERGRAM__PROTOCOL_MESSAGE__PAYLOAD_SET_PROFILE_REQUEST = 11,
  EVERGRAM__PROTOCOL_MESSAGE__PAYLOAD_REACTION = 12,
  EVERGRAM__PROTOCOL_MESSAGE__PAYLOAD_SEND_REACTION_REQUEST = 13,
  EVERGRAM__PROTOCOL_MESSAGE__PAYLOAD_TYPING_INDICATOR = 14,
  EVERGRAM__PROTOCOL_MESSAGE__PAYLOAD_ENCRYPTED_ENVELOPE = 15,
  EVERGRAM__PROTOCOL_MESSAGE__PAYLOAD_ERROR_RESPONSE = 16
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(EVERGRAM__PROTOCOL_MESSAGE__PAYLOAD__CASE)
} Evergram__ProtocolMessage__PayloadCase;

/*
 * Wrapper de protocolo
 */
struct  Evergram__ProtocolMessage
{
  ProtobufCMessage base;
  Evergram__ProtocolMessage__PayloadCase payload_case;
  union {
    Evergram__HandshakeRequest *handshake_request;
    Evergram__HandshakeResponse *handshake_response;
    Evergram__AuthRequest *auth_request;
    Evergram__AuthResponse *auth_response;
    Evergram__Message *message;
    Evergram__Chat *chat;
    Evergram__CreateChatRequest *create_chat_request;
    Evergram__AddParticipantRequest *add_participant_request;
    Evergram__RemoveParticipantRequest *remove_participant_request;
    Evergram__UserProfile *user_profile;
    Evergram__SetProfileRequest *set_profile_request;
    Evergram__Reaction *reaction;
    Evergram__SendReactionRequest *send_reaction_request;
    Evergram__TypingIndicator *typing_indicator;
    Evergram__EncryptedEnvelope *encrypted_envelope;
    Evergram__ErrorResponse *error_response;
  };
};
#define EVERGRAM__PROTOCOL_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&evergram__protocol_message__descriptor) \
    , EVERGRAM__PROTOCOL_MESSAGE__PAYLOAD__NOT_SET, {0} }


struct  Evergram__ErrorResponse
{
  ProtobufCMessage base;
  char *code;
  char *message;
  char *details;
};
#define EVERGRAM__ERROR_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&evergram__error_response__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/* Evergram__HandshakeRequest methods */
void   evergram__handshake_request__init
                     (Evergram__HandshakeRequest         *message);
size_t evergram__handshake_request__get_packed_size
                     (const Evergram__HandshakeRequest   *message);
size_t evergram__handshake_request__pack
                     (const Evergram__HandshakeRequest   *message,
                      uint8_t             *out);
size_t evergram__handshake_request__pack_to_buffer
                     (const Evergram__HandshakeRequest   *message,
                      ProtobufCBuffer     *buffer);
Evergram__HandshakeRequest *
       evergram__handshake_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   evergram__handshake_request__free_unpacked
                     (Evergram__HandshakeRequest *message,
                      ProtobufCAllocator *allocator);
/* Evergram__HandshakeResponse methods */
void   evergram__handshake_response__init
                     (Evergram__HandshakeResponse         *message);
size_t evergram__handshake_response__get_packed_size
                     (const Evergram__HandshakeResponse   *message);
size_t evergram__handshake_response__pack
                     (const Evergram__HandshakeResponse   *message,
                      uint8_t             *out);
size_t evergram__handshake_response__pack_to_buffer
                     (const Evergram__HandshakeResponse   *message,
                      ProtobufCBuffer     *buffer);
Evergram__HandshakeResponse *
       evergram__handshake_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   evergram__handshake_response__free_unpacked
                     (Evergram__HandshakeResponse *message,
                      ProtobufCAllocator *allocator);
/* Evergram__AuthRequest methods */
void   evergram__auth_request__init
                     (Evergram__AuthRequest         *message);
size_t evergram__auth_request__get_packed_size
                     (const Evergram__AuthRequest   *message);
size_t evergram__auth_request__pack
                     (const Evergram__AuthRequest   *message,
                      uint8_t             *out);
size_t evergram__auth_request__pack_to_buffer
                     (const Evergram__AuthRequest   *message,
                      ProtobufCBuffer     *buffer);
Evergram__AuthRequest *
       evergram__auth_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   evergram__auth_request__free_unpacked
                     (Evergram__AuthRequest *message,
                      ProtobufCAllocator *allocator);
/* Evergram__AuthResponse methods */
void   evergram__auth_response__init
                     (Evergram__AuthResponse         *message);
size_t evergram__auth_response__get_packed_size
                     (const Evergram__AuthResponse   *message);
size_t evergram__auth_response__pack
                     (const Evergram__AuthResponse   *message,
                      uint8_t             *out);
size_t evergram__auth_response__pack_to_buffer
                     (const Evergram__AuthResponse   *message,
                      ProtobufCBuffer     *buffer);
Evergram__AuthResponse *
       evergram__auth_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   evergram__auth_response__free_unpacked
                     (Evergram__AuthResponse *message,
                      ProtobufCAllocator *allocator);
/* Evergram__Message methods */
void   evergram__message__init
                     (Evergram__Message         *message);
size_t evergram__message__get_packed_size
                     (const Evergram__Message   *message);
size_t evergram__message__pack
                     (const Evergram__Message   *message,
                      uint8_t             *out);
size_t evergram__message__pack_to_buffer
                     (const Evergram__Message   *message,
                      ProtobufCBuffer     *buffer);
Evergram__Message *
       evergram__message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   evergram__message__free_unpacked
                     (Evergram__Message *message,
                      ProtobufCAllocator *allocator);
/* Evergram__Attachment methods */
void   evergram__attachment__init
                     (Evergram__Attachment         *message);
size_t evergram__attachment__get_packed_size
                     (const Evergram__Attachment   *message);
size_t evergram__attachment__pack
                     (const Evergram__Attachment   *message,
                      uint8_t             *out);
size_t evergram__attachment__pack_to_buffer
                     (const Evergram__Attachment   *message,
                      ProtobufCBuffer     *buffer);
Evergram__Attachment *
       evergram__attachment__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   evergram__attachment__free_unpacked
                     (Evergram__Attachment *message,
                      ProtobufCAllocator *allocator);
/* Evergram__Chat methods */
void   evergram__chat__init
                     (Evergram__Chat         *message);
size_t evergram__chat__get_packed_size
                     (const Evergram__Chat   *message);
size_t evergram__chat__pack
                     (const Evergram__Chat   *message,
                      uint8_t             *out);
size_t evergram__chat__pack_to_buffer
                     (const Evergram__Chat   *message,
                      ProtobufCBuffer     *buffer);
Evergram__Chat *
       evergram__chat__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   evergram__chat__free_unpacked
                     (Evergram__Chat *message,
                      ProtobufCAllocator *allocator);
/* Evergram__CreateChatRequest methods */
void   evergram__create_chat_request__init
                     (Evergram__CreateChatRequest         *message);
size_t evergram__create_chat_request__get_packed_size
                     (const Evergram__CreateChatRequest   *message);
size_t evergram__create_chat_request__pack
                     (const Evergram__CreateChatRequest   *message,
                      uint8_t             *out);
size_t evergram__create_chat_request__pack_to_buffer
                     (const Evergram__CreateChatRequest   *message,
                      ProtobufCBuffer     *buffer);
Evergram__CreateChatRequest *
       evergram__create_chat_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   evergram__create_chat_request__free_unpacked
                     (Evergram__CreateChatRequest *message,
                      ProtobufCAllocator *allocator);
/* Evergram__AddParticipantRequest methods */
void   evergram__add_participant_request__init
                     (Evergram__AddParticipantRequest         *message);
size_t evergram__add_participant_request__get_packed_size
                     (const Evergram__AddParticipantRequest   *message);
size_t evergram__add_participant_request__pack
                     (const Evergram__AddParticipantRequest   *message,
                      uint8_t             *out);
size_t evergram__add_participant_request__pack_to_buffer
                     (const Evergram__AddParticipantRequest   *message,
                      ProtobufCBuffer     *buffer);
Evergram__AddParticipantRequest *
       evergram__add_participant_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   evergram__add_participant_request__free_unpacked
                     (Evergram__AddParticipantRequest *message,
                      ProtobufCAllocator *allocator);
/* Evergram__RemoveParticipantRequest methods */
void   evergram__remove_participant_request__init
                     (Evergram__RemoveParticipantRequest         *message);
size_t evergram__remove_participant_request__get_packed_size
                     (const Evergram__RemoveParticipantRequest   *message);
size_t evergram__remove_participant_request__pack
                     (const Evergram__RemoveParticipantRequest   *message,
                      uint8_t             *out);
size_t evergram__remove_participant_request__pack_to_buffer
                     (const Evergram__RemoveParticipantRequest   *message,
                      ProtobufCBuffer     *buffer);
Evergram__RemoveParticipantRequest *
       evergram__remove_participant_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   evergram__remove_participant_request__free_unpacked
                     (Evergram__RemoveParticipantRequest *message,
                      ProtobufCAllocator *allocator);
/* Evergram__UserProfile methods */
void   evergram__user_profile__init
                     (Evergram__UserProfile         *message);
size_t evergram__user_profile__get_packed_size
                     (const Evergram__UserProfile   *message);
size_t evergram__user_profile__pack
                     (const Evergram__UserProfile   *message,
                      uint8_t             *out);
size_t evergram__user_profile__pack_to_buffer
                     (const Evergram__UserProfile   *message,
                      ProtobufCBuffer     *buffer);
Evergram__UserProfile *
       evergram__user_profile__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   evergram__user_profile__free_unpacked
                     (Evergram__UserProfile *message,
                      ProtobufCAllocator *allocator);
/* Evergram__SetProfileRequest methods */
void   evergram__set_profile_request__init
                     (Evergram__SetProfileRequest         *message);
size_t evergram__set_profile_request__get_packed_size
                     (const Evergram__SetProfileRequest   *message);
size_t evergram__set_profile_request__pack
                     (const Evergram__SetProfileRequest   *message,
                      uint8_t             *out);
size_t evergram__set_profile_request__pack_to_buffer
                     (const Evergram__SetProfileRequest   *message,
                      ProtobufCBuffer     *buffer);
Evergram__SetProfileRequest *
       evergram__set_profile_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   evergram__set_profile_request__free_unpacked
                     (Evergram__SetProfileRequest *message,
                      ProtobufCAllocator *allocator);
/* Evergram__Reaction methods */
void   evergram__reaction__init
                     (Evergram__Reaction         *message);
size_t evergram__reaction__get_packed_size
                     (const Evergram__Reaction   *message);
size_t evergram__reaction__pack
                     (const Evergram__Reaction   *message,
                      uint8_t             *out);
size_t evergram__reaction__pack_to_buffer
                     (const Evergram__Reaction   *message,
                      ProtobufCBuffer     *buffer);
Evergram__Reaction *
       evergram__reaction__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   evergram__reaction__free_unpacked
                     (Evergram__Reaction *message,
                      ProtobufCAllocator *allocator);
/* Evergram__SendReactionRequest methods */
void   evergram__send_reaction_request__init
                     (Evergram__SendReactionRequest         *message);
size_t evergram__send_reaction_request__get_packed_size
                     (const Evergram__SendReactionRequest   *message);
size_t evergram__send_reaction_request__pack
                     (const Evergram__SendReactionRequest   *message,
                      uint8_t             *out);
size_t evergram__send_reaction_request__pack_to_buffer
                     (const Evergram__SendReactionRequest   *message,
                      ProtobufCBuffer     *buffer);
Evergram__SendReactionRequest *
       evergram__send_reaction_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   evergram__send_reaction_request__free_unpacked
                     (Evergram__SendReactionRequest *message,
                      ProtobufCAllocator *allocator);
/* Evergram__TypingIndicator methods */
void   evergram__typing_indicator__init
                     (Evergram__TypingIndicator         *message);
size_t evergram__typing_indicator__get_packed_size
                     (const Evergram__TypingIndicator   *message);
size_t evergram__typing_indicator__pack
                     (const Evergram__TypingIndicator   *message,
                      uint8_t             *out);
size_t evergram__typing_indicator__pack_to_buffer
                     (const Evergram__TypingIndicator   *message,
                      ProtobufCBuffer     *buffer);
Evergram__TypingIndicator *
       evergram__typing_indicator__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   evergram__typing_indicator__free_unpacked
                     (Evergram__TypingIndicator *message,
                      ProtobufCAllocator *allocator);
/* Evergram__EncryptedEnvelope methods */
void   evergram__encrypted_envelope__init
                     (Evergram__EncryptedEnvelope         *message);
size_t evergram__encrypted_envelope__get_packed_size
                     (const Evergram__EncryptedEnvelope   *message);
size_t evergram__encrypted_envelope__pack
                     (const Evergram__EncryptedEnvelope   *message,
                      uint8_t             *out);
size_t evergram__encrypted_envelope__pack_to_buffer
                     (const Evergram__EncryptedEnvelope   *message,
                      ProtobufCBuffer     *buffer);
Evergram__EncryptedEnvelope *
       evergram__encrypted_envelope__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   evergram__encrypted_envelope__free_unpacked
                     (Evergram__EncryptedEnvelope *message,
                      ProtobufCAllocator *allocator);
/* Evergram__ProtocolMessage methods */
void   evergram__protocol_message__init
                     (Evergram__ProtocolMessage         *message);
size_t evergram__protocol_message__get_packed_size
                     (const Evergram__ProtocolMessage   *message);
size_t evergram__protocol_message__pack
                     (const Evergram__ProtocolMessage   *message,
                      uint8_t             *out);
size_t evergram__protocol_message__pack_to_buffer
                     (const Evergram__ProtocolMessage   *message,
                      ProtobufCBuffer     *buffer);
Evergram__ProtocolMessage *
       evergram__protocol_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   evergram__protocol_message__free_unpacked
                     (Evergram__ProtocolMessage *message,
                      ProtobufCAllocator *allocator);
/* Evergram__ErrorResponse methods */
void   evergram__error_response__init
                     (Evergram__ErrorResponse         *message);
size_t evergram__error_response__get_packed_size
                     (const Evergram__ErrorResponse   *message);
size_t evergram__error_response__pack
                     (const Evergram__ErrorResponse   *message,
                      uint8_t             *out);
size_t evergram__error_response__pack_to_buffer
                     (const Evergram__ErrorResponse   *message,
                      ProtobufCBuffer     *buffer);
Evergram__ErrorResponse *
       evergram__error_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   evergram__error_response__free_unpacked
                     (Evergram__ErrorResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Evergram__HandshakeRequest_Closure)
                 (const Evergram__HandshakeRequest *message,
                  void *closure_data);
typedef void (*Evergram__HandshakeResponse_Closure)
                 (const Evergram__HandshakeResponse *message,
                  void *closure_data);
typedef void (*Evergram__AuthRequest_Closure)
                 (const Evergram__AuthRequest *message,
                  void *closure_data);
typedef void (*Evergram__AuthResponse_Closure)
                 (const Evergram__AuthResponse *message,
                  void *closure_data);
typedef void (*Evergram__Message_Closure)
                 (const Evergram__Message *message,
                  void *closure_data);
typedef void (*Evergram__Attachment_Closure)
                 (const Evergram__Attachment *message,
                  void *closure_data);
typedef void (*Evergram__Chat_Closure)
                 (const Evergram__Chat *message,
                  void *closure_data);
typedef void (*Evergram__CreateChatRequest_Closure)
                 (const Evergram__CreateChatRequest *message,
                  void *closure_data);
typedef void (*Evergram__AddParticipantRequest_Closure)
                 (const Evergram__AddParticipantRequest *message,
                  void *closure_data);
typedef void (*Evergram__RemoveParticipantRequest_Closure)
                 (const Evergram__RemoveParticipantRequest *message,
                  void *closure_data);
typedef void (*Evergram__UserProfile_Closure)
                 (const Evergram__UserProfile *message,
                  void *closure_data);
typedef void (*Evergram__SetProfileRequest_Closure)
                 (const Evergram__SetProfileRequest *message,
                  void *closure_data);
typedef void (*Evergram__Reaction_Closure)
                 (const Evergram__Reaction *message,
                  void *closure_data);
typedef void (*Evergram__SendReactionRequest_Closure)
                 (const Evergram__SendReactionRequest *message,
                  void *closure_data);
typedef void (*Evergram__TypingIndicator_Closure)
                 (const Evergram__TypingIndicator *message,
                  void *closure_data);
typedef void (*Evergram__EncryptedEnvelope_Closure)
                 (const Evergram__EncryptedEnvelope *message,
                  void *closure_data);
typedef void (*Evergram__ProtocolMessage_Closure)
                 (const Evergram__ProtocolMessage *message,
                  void *closure_data);
typedef void (*Evergram__ErrorResponse_Closure)
                 (const Evergram__ErrorResponse *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    evergram__message_type__descriptor;
extern const ProtobufCEnumDescriptor    evergram__message_status__descriptor;
extern const ProtobufCEnumDescriptor    evergram__chat_type__descriptor;
extern const ProtobufCMessageDescriptor evergram__handshake_request__descriptor;
extern const ProtobufCMessageDescriptor evergram__handshake_response__descriptor;
extern const ProtobufCMessageDescriptor evergram__auth_request__descriptor;
extern const ProtobufCMessageDescriptor evergram__auth_response__descriptor;
extern const ProtobufCMessageDescriptor evergram__message__descriptor;
extern const ProtobufCMessageDescriptor evergram__attachment__descriptor;
extern const ProtobufCMessageDescriptor evergram__chat__descriptor;
extern const ProtobufCMessageDescriptor evergram__create_chat_request__descriptor;
extern const ProtobufCMessageDescriptor evergram__add_participant_request__descriptor;
extern const ProtobufCMessageDescriptor evergram__remove_participant_request__descriptor;
extern const ProtobufCMessageDescriptor evergram__user_profile__descriptor;
extern const ProtobufCMessageDescriptor evergram__set_profile_request__descriptor;
extern const ProtobufCMessageDescriptor evergram__reaction__descriptor;
extern const ProtobufCMessageDescriptor evergram__send_reaction_request__descriptor;
extern const ProtobufCMessageDescriptor evergram__typing_indicator__descriptor;
extern const ProtobufCMessageDescriptor evergram__encrypted_envelope__descriptor;
extern const ProtobufCMessageDescriptor evergram__protocol_message__descriptor;
extern const ProtobufCMessageDescriptor evergram__error_response__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_evergram_2eproto__INCLUDED */
