/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: evergram.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "evergram.pb-c.h"
void   evergram__client_hello__init
                     (Evergram__ClientHello         *message)
{
  static const Evergram__ClientHello init_value = EVERGRAM__CLIENT_HELLO__INIT;
  *message = init_value;
}
size_t evergram__client_hello__get_packed_size
                     (const Evergram__ClientHello *message)
{
  assert(message->base.descriptor == &evergram__client_hello__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t evergram__client_hello__pack
                     (const Evergram__ClientHello *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &evergram__client_hello__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t evergram__client_hello__pack_to_buffer
                     (const Evergram__ClientHello *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &evergram__client_hello__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Evergram__ClientHello *
       evergram__client_hello__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Evergram__ClientHello *)
     protobuf_c_message_unpack (&evergram__client_hello__descriptor,
                                allocator, len, data);
}
void   evergram__client_hello__free_unpacked
                     (Evergram__ClientHello *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &evergram__client_hello__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   evergram__server_hello__init
                     (Evergram__ServerHello         *message)
{
  static const Evergram__ServerHello init_value = EVERGRAM__SERVER_HELLO__INIT;
  *message = init_value;
}
size_t evergram__server_hello__get_packed_size
                     (const Evergram__ServerHello *message)
{
  assert(message->base.descriptor == &evergram__server_hello__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t evergram__server_hello__pack
                     (const Evergram__ServerHello *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &evergram__server_hello__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t evergram__server_hello__pack_to_buffer
                     (const Evergram__ServerHello *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &evergram__server_hello__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Evergram__ServerHello *
       evergram__server_hello__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Evergram__ServerHello *)
     protobuf_c_message_unpack (&evergram__server_hello__descriptor,
                                allocator, len, data);
}
void   evergram__server_hello__free_unpacked
                     (Evergram__ServerHello *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &evergram__server_hello__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   evergram__chat_message__init
                     (Evergram__ChatMessage         *message)
{
  static const Evergram__ChatMessage init_value = EVERGRAM__CHAT_MESSAGE__INIT;
  *message = init_value;
}
size_t evergram__chat_message__get_packed_size
                     (const Evergram__ChatMessage *message)
{
  assert(message->base.descriptor == &evergram__chat_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t evergram__chat_message__pack
                     (const Evergram__ChatMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &evergram__chat_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t evergram__chat_message__pack_to_buffer
                     (const Evergram__ChatMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &evergram__chat_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Evergram__ChatMessage *
       evergram__chat_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Evergram__ChatMessage *)
     protobuf_c_message_unpack (&evergram__chat_message__descriptor,
                                allocator, len, data);
}
void   evergram__chat_message__free_unpacked
                     (Evergram__ChatMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &evergram__chat_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   evergram__reaction__init
                     (Evergram__Reaction         *message)
{
  static const Evergram__Reaction init_value = EVERGRAM__REACTION__INIT;
  *message = init_value;
}
size_t evergram__reaction__get_packed_size
                     (const Evergram__Reaction *message)
{
  assert(message->base.descriptor == &evergram__reaction__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t evergram__reaction__pack
                     (const Evergram__Reaction *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &evergram__reaction__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t evergram__reaction__pack_to_buffer
                     (const Evergram__Reaction *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &evergram__reaction__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Evergram__Reaction *
       evergram__reaction__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Evergram__Reaction *)
     protobuf_c_message_unpack (&evergram__reaction__descriptor,
                                allocator, len, data);
}
void   evergram__reaction__free_unpacked
                     (Evergram__Reaction *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &evergram__reaction__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   evergram__typing_indicator__init
                     (Evergram__TypingIndicator         *message)
{
  static const Evergram__TypingIndicator init_value = EVERGRAM__TYPING_INDICATOR__INIT;
  *message = init_value;
}
size_t evergram__typing_indicator__get_packed_size
                     (const Evergram__TypingIndicator *message)
{
  assert(message->base.descriptor == &evergram__typing_indicator__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t evergram__typing_indicator__pack
                     (const Evergram__TypingIndicator *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &evergram__typing_indicator__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t evergram__typing_indicator__pack_to_buffer
                     (const Evergram__TypingIndicator *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &evergram__typing_indicator__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Evergram__TypingIndicator *
       evergram__typing_indicator__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Evergram__TypingIndicator *)
     protobuf_c_message_unpack (&evergram__typing_indicator__descriptor,
                                allocator, len, data);
}
void   evergram__typing_indicator__free_unpacked
                     (Evergram__TypingIndicator *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &evergram__typing_indicator__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   evergram__system_event__init
                     (Evergram__SystemEvent         *message)
{
  static const Evergram__SystemEvent init_value = EVERGRAM__SYSTEM_EVENT__INIT;
  *message = init_value;
}
size_t evergram__system_event__get_packed_size
                     (const Evergram__SystemEvent *message)
{
  assert(message->base.descriptor == &evergram__system_event__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t evergram__system_event__pack
                     (const Evergram__SystemEvent *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &evergram__system_event__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t evergram__system_event__pack_to_buffer
                     (const Evergram__SystemEvent *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &evergram__system_event__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Evergram__SystemEvent *
       evergram__system_event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Evergram__SystemEvent *)
     protobuf_c_message_unpack (&evergram__system_event__descriptor,
                                allocator, len, data);
}
void   evergram__system_event__free_unpacked
                     (Evergram__SystemEvent *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &evergram__system_event__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   evergram__envelope__init
                     (Evergram__Envelope         *message)
{
  static const Evergram__Envelope init_value = EVERGRAM__ENVELOPE__INIT;
  *message = init_value;
}
size_t evergram__envelope__get_packed_size
                     (const Evergram__Envelope *message)
{
  assert(message->base.descriptor == &evergram__envelope__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t evergram__envelope__pack
                     (const Evergram__Envelope *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &evergram__envelope__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t evergram__envelope__pack_to_buffer
                     (const Evergram__Envelope *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &evergram__envelope__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Evergram__Envelope *
       evergram__envelope__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Evergram__Envelope *)
     protobuf_c_message_unpack (&evergram__envelope__descriptor,
                                allocator, len, data);
}
void   evergram__envelope__free_unpacked
                     (Evergram__Envelope *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &evergram__envelope__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor evergram__client_hello__field_descriptors[6] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__ClientHello, version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ephemeral_public_key",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Evergram__ClientHello, ephemeral_public_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nonce",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Evergram__ClientHello, nonce),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_id",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__ClientHello, device_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wallet_address",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__ClientHello, wallet_address),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signature",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Evergram__ClientHello, signature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned evergram__client_hello__field_indices_by_name[] = {
  3,   /* field[3] = device_id */
  1,   /* field[1] = ephemeral_public_key */
  2,   /* field[2] = nonce */
  5,   /* field[5] = signature */
  0,   /* field[0] = version */
  4,   /* field[4] = wallet_address */
};
static const ProtobufCIntRange evergram__client_hello__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor evergram__client_hello__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "evergram.ClientHello",
  "ClientHello",
  "Evergram__ClientHello",
  "evergram",
  sizeof(Evergram__ClientHello),
  6,
  evergram__client_hello__field_descriptors,
  evergram__client_hello__field_indices_by_name,
  1,  evergram__client_hello__number_ranges,
  (ProtobufCMessageInit) evergram__client_hello__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor evergram__server_hello__field_descriptors[5] =
{
  {
    "server_public_key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Evergram__ServerHello, server_public_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nonce",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Evergram__ServerHello, nonce),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "session_id",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__ServerHello, session_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "success",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Evergram__ServerHello, success),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error_message",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__ServerHello, error_message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned evergram__server_hello__field_indices_by_name[] = {
  4,   /* field[4] = error_message */
  1,   /* field[1] = nonce */
  0,   /* field[0] = server_public_key */
  2,   /* field[2] = session_id */
  3,   /* field[3] = success */
};
static const ProtobufCIntRange evergram__server_hello__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor evergram__server_hello__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "evergram.ServerHello",
  "ServerHello",
  "Evergram__ServerHello",
  "evergram",
  sizeof(Evergram__ServerHello),
  5,
  evergram__server_hello__field_descriptors,
  evergram__server_hello__field_indices_by_name,
  1,  evergram__server_hello__number_ranges,
  (ProtobufCMessageInit) evergram__server_hello__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor evergram__chat_message__field_descriptors[6] =
{
  {
    "chat_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__ChatMessage, chat_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sender_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__ChatMessage, sender_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "content",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__ChatMessage, content),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Evergram__ChatMessage, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Evergram__ChatMessage, type),
    &evergram__message_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reply_to",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__ChatMessage, reply_to),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned evergram__chat_message__field_indices_by_name[] = {
  0,   /* field[0] = chat_id */
  2,   /* field[2] = content */
  5,   /* field[5] = reply_to */
  1,   /* field[1] = sender_id */
  3,   /* field[3] = timestamp */
  4,   /* field[4] = type */
};
static const ProtobufCIntRange evergram__chat_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor evergram__chat_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "evergram.ChatMessage",
  "ChatMessage",
  "Evergram__ChatMessage",
  "evergram",
  sizeof(Evergram__ChatMessage),
  6,
  evergram__chat_message__field_descriptors,
  evergram__chat_message__field_indices_by_name,
  1,  evergram__chat_message__number_ranges,
  (ProtobufCMessageInit) evergram__chat_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor evergram__reaction__field_descriptors[4] =
{
  {
    "chat_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__Reaction, chat_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__Reaction, message_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "emoji",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__Reaction, emoji),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "add",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Evergram__Reaction, add),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned evergram__reaction__field_indices_by_name[] = {
  3,   /* field[3] = add */
  0,   /* field[0] = chat_id */
  2,   /* field[2] = emoji */
  1,   /* field[1] = message_id */
};
static const ProtobufCIntRange evergram__reaction__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor evergram__reaction__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "evergram.Reaction",
  "Reaction",
  "Evergram__Reaction",
  "evergram",
  sizeof(Evergram__Reaction),
  4,
  evergram__reaction__field_descriptors,
  evergram__reaction__field_indices_by_name,
  1,  evergram__reaction__number_ranges,
  (ProtobufCMessageInit) evergram__reaction__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor evergram__typing_indicator__field_descriptors[2] =
{
  {
    "chat_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__TypingIndicator, chat_id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_typing",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Evergram__TypingIndicator, is_typing),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned evergram__typing_indicator__field_indices_by_name[] = {
  0,   /* field[0] = chat_id */
  1,   /* field[1] = is_typing */
};
static const ProtobufCIntRange evergram__typing_indicator__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor evergram__typing_indicator__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "evergram.TypingIndicator",
  "TypingIndicator",
  "Evergram__TypingIndicator",
  "evergram",
  sizeof(Evergram__TypingIndicator),
  2,
  evergram__typing_indicator__field_descriptors,
  evergram__typing_indicator__field_indices_by_name,
  1,  evergram__typing_indicator__number_ranges,
  (ProtobufCMessageInit) evergram__typing_indicator__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor evergram__system_event__field_descriptors[2] =
{
  {
    "event_type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__SystemEvent, event_type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Evergram__SystemEvent, data),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned evergram__system_event__field_indices_by_name[] = {
  1,   /* field[1] = data */
  0,   /* field[0] = event_type */
};
static const ProtobufCIntRange evergram__system_event__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor evergram__system_event__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "evergram.SystemEvent",
  "SystemEvent",
  "Evergram__SystemEvent",
  "evergram",
  sizeof(Evergram__SystemEvent),
  2,
  evergram__system_event__field_descriptors,
  evergram__system_event__field_indices_by_name,
  1,  evergram__system_event__number_ranges,
  (ProtobufCMessageInit) evergram__system_event__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor evergram__envelope__field_descriptors[8] =
{
  {
    "client_hello",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Evergram__Envelope, payload_case),
    offsetof(Evergram__Envelope, client_hello),
    &evergram__client_hello__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "server_hello",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Evergram__Envelope, payload_case),
    offsetof(Evergram__Envelope, server_hello),
    &evergram__server_hello__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "chat_message",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Evergram__Envelope, payload_case),
    offsetof(Evergram__Envelope, chat_message),
    &evergram__chat_message__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reaction",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Evergram__Envelope, payload_case),
    offsetof(Evergram__Envelope, reaction),
    &evergram__reaction__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "typing",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Evergram__Envelope, payload_case),
    offsetof(Evergram__Envelope, typing),
    &evergram__typing_indicator__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "system_event",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Evergram__Envelope, payload_case),
    offsetof(Evergram__Envelope, system_event),
    &evergram__system_event__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nonce",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Evergram__Envelope, nonce),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mac",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Evergram__Envelope, mac),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned evergram__envelope__field_indices_by_name[] = {
  2,   /* field[2] = chat_message */
  0,   /* field[0] = client_hello */
  7,   /* field[7] = mac */
  6,   /* field[6] = nonce */
  3,   /* field[3] = reaction */
  1,   /* field[1] = server_hello */
  5,   /* field[5] = system_event */
  4,   /* field[4] = typing */
};
static const ProtobufCIntRange evergram__envelope__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor evergram__envelope__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "evergram.Envelope",
  "Envelope",
  "Evergram__Envelope",
  "evergram",
  sizeof(Evergram__Envelope),
  8,
  evergram__envelope__field_descriptors,
  evergram__envelope__field_indices_by_name,
  1,  evergram__envelope__number_ranges,
  (ProtobufCMessageInit) evergram__envelope__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue evergram__message_type__enum_values_by_number[5] =
{
  { "UNKNOWN", "EVERGRAM__MESSAGE_TYPE__UNKNOWN", 0 },
  { "TEXT_MESSAGE", "EVERGRAM__MESSAGE_TYPE__TEXT_MESSAGE", 1 },
  { "REACTION", "EVERGRAM__MESSAGE_TYPE__REACTION", 2 },
  { "TYPING_INDICATOR", "EVERGRAM__MESSAGE_TYPE__TYPING_INDICATOR", 3 },
  { "SYSTEM_EVENT", "EVERGRAM__MESSAGE_TYPE__SYSTEM_EVENT", 4 },
};
static const ProtobufCIntRange evergram__message_type__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex evergram__message_type__enum_values_by_name[5] =
{
  { "REACTION", 2 },
  { "SYSTEM_EVENT", 4 },
  { "TEXT_MESSAGE", 1 },
  { "TYPING_INDICATOR", 3 },
  { "UNKNOWN", 0 },
};
const ProtobufCEnumDescriptor evergram__message_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "evergram.MessageType",
  "MessageType",
  "Evergram__MessageType",
  "evergram",
  5,
  evergram__message_type__enum_values_by_number,
  5,
  evergram__message_type__enum_values_by_name,
  1,
  evergram__message_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
