/*
 * gen_xahau_vectors.mjs — emits tests/xahau_vectors.h with signed Xahau/XRPL
 * payment transactions produced by the `xrpl` package, which is exactly what
 * the TypeScript xahau-tip-bot example uses to reach the ledger.
 *
 * The C side serializes and signs the same transaction itself, so a byte-for-byte
 * match here is the proof that its hand-written XRPL binary encoding is right —
 * something no amount of offline reasoning about field codes could establish.
 *
 *   TS_SDK=/path/to/evergram-sdk node tools/gen_xahau_vectors.mjs \
 *       tests/xahau_vectors.h
 *
 * The inputs are fixed, so the output is deterministic; ed25519 signatures are
 * deterministic too, which is what makes byte equality the right assertion.
 */
import { writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { resolve } from "node:path";

const require = createRequire(import.meta.url);

const sdkRoot = process.env.TS_SDK;
if (!sdkRoot) {
  console.error("TS_SDK must point at an evergram-sdk checkout (for its node_modules)");
  process.exit(1);
}

const { Wallet, hashes } = require(resolve(sdkRoot, "node_modules/xrpl"));
const { encodeSeed } = require(resolve(sdkRoot, "node_modules/ripple-address-codec"));
const codec = require(resolve(sdkRoot, "node_modules/ripple-binary-codec"));

/* The same seed the interop vectors use, so both generators describe one wallet. */
const entropy = "db7fc7a261e8082cc0f3fdb3b3f15f95";
const seed = encodeSeed(Buffer.from(entropy, "hex"), "ed25519");
const wallet = Wallet.fromSeed(seed);

const destination = "rPT1Sjq2YGrBMTttX4GZHjKu9dyfzbpAYe";

/* Xahau reports a network id above 1024, so its transactions carry one; XRPL
 * mainnet does not, which is why both shapes are pinned. */
const cases = [
  {
    name: "XAH_WITH_NETWORK_ID",
    tx: {
      TransactionType: "Payment",
      Account: wallet.address,
      Destination: destination,
      Amount: "5000000",
      Fee: "12",
      Sequence: 42,
      LastLedgerSequence: 1000,
      NetworkID: 21337,
    },
  },
  {
    name: "XAH_WITHOUT_NETWORK_ID",
    tx: {
      TransactionType: "Payment",
      Account: wallet.address,
      Destination: destination,
      Amount: "1",
      Fee: "10",
      Sequence: 7,
      LastLedgerSequence: 900,
    },
  },
];

const lines = [];
lines.push("/*");
lines.push(" * Golden Xahau/XRPL payment vectors, generated by");
lines.push(" * tools/gen_xahau_vectors.mjs using the `xrpl` package — the same library the");
lines.push(" * TypeScript xahau-tip-bot example submits with. The C side builds these");
lines.push(" * transactions itself, so byte equality proves its XRPL binary encoding and");
lines.push(" * ed25519 signing are correct. Do not edit by hand.");
lines.push(" */");
lines.push("#ifndef EVERGRAM_TEST_XAHAU_VECTORS_H");
lines.push("#define EVERGRAM_TEST_XAHAU_VECTORS_H");
lines.push("");
lines.push(`#define XAH_SEED "${seed}"`);
lines.push(`#define XAH_ACCOUNT "${wallet.address}"`);
lines.push(`#define XAH_PUBLIC_KEY_HEX "${wallet.publicKey}"`);
/* The identity's own key pair: the private half is what signs the payment. */
lines.push(`#define XAH_PRIVATE_KEY_HEX "${wallet.privateKey}"`);
lines.push(`#define XAH_DESTINATION "${destination}"`);
lines.push("");

for (const { name, tx } of cases) {
  const signed = wallet.sign(tx);
  /* Independent check of the hash rule the C side must reproduce. */
  const expectedHash = hashes.hashSignedTx(signed.tx_blob);
  if (expectedHash !== signed.hash) {
    console.error("hash disagreement inside the reference library; refusing to emit");
    process.exit(1);
  }
  const decoded = codec.decode(signed.tx_blob);
  if (decoded.hash !== undefined && decoded.hash !== signed.hash) {
    console.error("decoded hash disagreement; refusing to emit");
    process.exit(1);
  }

  lines.push(`/* ${JSON.stringify(tx)} */`);
  lines.push(`#define ${name}_AMOUNT "${tx.Amount}"`);
  lines.push(`#define ${name}_FEE "${tx.Fee}"`);
  lines.push(`#define ${name}_SEQUENCE ${tx.Sequence}`);
  lines.push(`#define ${name}_LAST_LEDGER_SEQUENCE ${tx.LastLedgerSequence}`);
  if (tx.NetworkID !== undefined) {
    lines.push(`#define ${name}_NETWORK_ID ${tx.NetworkID}`);
  }
  /* What the signature actually commits to: the transaction *with* its
   * SigningPubKey and without TxnSignature. Encoding the bare tx would leave
   * the key out and describe a payload nothing ever signs. */
  const signingData = codec.encodeForSigning({ ...tx, SigningPubKey: wallet.publicKey });
  if (!signingData.includes(wallet.publicKey.slice(2))) {
    console.error("the signing payload does not carry the public key; refusing to emit");
    process.exit(1);
  }
  lines.push(`#define ${name}_SIGNING_DATA "${signingData}"`);
  lines.push(`#define ${name}_BLOB "${signed.tx_blob}"`);
  lines.push(`#define ${name}_HASH "${signed.hash}"`);
  lines.push("");
}

lines.push("#endif /* EVERGRAM_TEST_XAHAU_VECTORS_H */");
lines.push("");

const target = process.argv[2];
if (!target) {
  process.stdout.write(lines.join("\n"));
} else {
  writeFileSync(target, lines.join("\n"));
  console.log("wrote", target);
  console.log("account:", wallet.address);
  for (const { name } of cases) console.log("vector:", name);
}
